import type { LevelConfig } from '../types';
import { createMusicProfile } from '../musicHelpers';

export const ASTEROID_BELT_ALPHA_LEVEL: LevelConfig = {
  name: 'Asteroid Belt Alpha',
  planetName: 'Kepler-7b',
  destination: 'Outer debris route to Kepler-7b',
  visualTheme: 'Cold blue asteroid wash with sparse neon dust and crisp starfields.',
  coreGameplayIdea: 'A readable opener focused on moving through broken rock traffic while learning encounter spacing.',
  pacingSummary: 'Short scouting skirmishes, then denser asteroid rhythm, then a calm final approach.',
  enemyCompositionSummary: 'Mostly scouts with light fighter support.',
  hazardSummary: 'Ambient asteroid drift and modest debris clusters.',
  bossConcept: 'No boss; the level teaches motion and target priority.',
  difficultyRole: 'Warm-up and onboarding for the campaign arc.',
  journeyNote: 'The run begins in civilized shipping lanes and pushes outward into riskier space.',
  bgColor: '#000011',
  accentColor: 0x00ccff,
  nebulaColor: 0x1133aa,
  nebulaAlpha: 0.08,
  colorGrade: { brightness: 0.02, contrast: 1.03, saturation: 1.05 },
  planetPalette: [0x2266aa, 0x4488cc],
  enemies: [
    { type: 'scout', weight: 80 },
    { type: 'fighter', weight: 20 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.0,
  levelDistance: 7200,
  hasBoss: false,
  boss: null,
  bossTriggerProgress: 0.8,
  asteroidInterval: 5000,
  sections: [
    {
      id: 'alpha-scout-screen',
      label: 'Scout Screen',
      startProgress: 0,
      endProgress: 0.35,
      phase: 'intro',
      summary: 'Soft opening with predictable scouts and slow-moving rocks.',
      musicIntensity: 0.2,
    },
    {
      id: 'alpha-debris-burst',
      label: 'Debris Burst',
      startProgress: 0.35,
      endProgress: 0.72,
      phase: 'build',
      summary: 'Asteroid density rises and fighters start flanking from the edges.',
      asteroidInterval: 4200,
      hazardEvents: [{ type: 'debris-surge', cadenceMs: 2200, intensity: 0.35 }],
      musicIntensity: 0.45,
    },
    {
      id: 'alpha-final-lane',
      label: 'Clear Lane',
      startProgress: 0.72,
      endProgress: 1,
      phase: 'climax',
      summary: 'A cleaner run that feels like a confident arrival.',
      musicIntensity: 0.35,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Cold Departure',
      mood: 'focused optimism',
      tempoFeel: 'steady cruise',
      musicalStyle: 'retro synth arpeggio with airy pulse accents',
      intensity: 'low to medium',
      shiftMoments: ['Add pulse stabs when debris density rises around mid-level.'],
      bossCueName: 'Cold Departure Surge',
    },
    {
      tempo: 108,
      rootHz: 110,
      stepsPerBeat: 4,
      masterGain: 0.95,
      bass: {
        waveform: 'triangle',
        pattern: [0, null, null, null, 7, null, null, null, 12, null, null, null, 7, null, null, null],
        gain: 0.18,
        durationSteps: 3,
      },
      pulse: {
        waveform: 'square',
        pattern: [12, null, 12, null, 7, null, 12, null, 14, null, 12, null, 7, null, 5, null],
        gain: 0.05,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1800,
      },
      lead: {
        waveform: 'sine',
        pattern: [null, 12, null, 14, null, 12, null, 7, null, 12, null, 14, null, 19, null, 14],
        gain: 0.045,
        durationSteps: 2,
        octaveShift: 1,
      },
    },
    {
      tempo: 118,
      masterGain: 1.05,
      lead: { waveform: 'triangle', gain: 0.055 },
      pulse: { gain: 0.06 },
    }
  ),
};
