import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const ASTEROID_BELT_ALPHA_LEVEL: LevelConfig = {
  name: 'Solar Slipstream',
  planetName: 'Helion Delta',
  destination: 'Solar-current runway feeding Helion Delta trade lanes',
  visualTheme: 'Cobalt void ribbons with bright ion wakes and high-contrast debris silhouettes.',
  coreGameplayIdea: 'A friendly but cinematic opener that teaches lane-reading through readable hazard telegraphs.',
  pacingSummary: 'Warm-up scouts, guided debris pulses, then one stylish corridor set-piece with a calm release.',
  enemyCompositionSummary: 'Scouts lead while fighters test early spacing discipline.',
  hazardSummary: 'Low-intensity debris surges, mirrored cross-lane rocks, and a forgiving corridor.',
  bossConcept: 'No boss in this opener; clarity and flow are the real tutorial exam.',
  difficultyRole: 'Onboarding level with strong readability and confidence building.',
  journeyNote: 'Pilots launch into a luminous current that feels more like a concert overture than a warzone.',
  bgColor: '#07122a',
  accentColor: 0x59d7ff,
  nebulaColor: 0x1b468e,
  nebulaAlpha: 0.17,
  colorGrade: { brightness: 0.11, contrast: 1.04, saturation: 1.12 },
  planetPalette: [0x2d76c6, 0x75c9ff],
  enemies: [
    { type: 'scout', weight: 72 },
    { type: 'fighter', weight: 28 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.03,
  levelDistance: 11200,
  hasBoss: false,
  boss: null,
  bossTriggerProgress: 0.82,
  asteroidInterval: 4700,
  sections: [
    {
      id: 'slipstream-entry',
      label: 'Launch Corridor',
      startProgress: 0,
      endProgress: 0.2,
      phase: 'intro',
      summary: 'High-contrast scout arrivals with generous dodge lanes.',
      musicIntensity: 0.28,
    },
    {
      id: 'slipstream-debris-ribbon',
      label: 'Debris Ribbon',
      startProgress: 0.2,
      endProgress: 0.44,
      phase: 'build',
      summary: 'Short debris surges establish rhythmic hazard telegraphing.',
      asteroidInterval: 3800,
      hazardEvents: [{ type: 'debris-surge', cadenceMs: 2200, intensity: 0.35 }],
      musicIntensity: 0.48,
    },
    {
      id: 'slipstream-prism-cross',
      label: 'Prism Crossfire',
      startProgress: 0.44,
      endProgress: 0.64,
      phase: 'hazard',
      summary: 'Mirrored rocks frame clear lanes while fighters test side awareness.',
      encounterSizeOverride: { min: 2, max: 2 },
      hazardEvents: [{ type: 'ring-crossfire', cadenceMs: 1900, intensity: 0.45 }],
      musicIntensity: 0.62,
    },
    {
      id: 'slipstream-canyon-lite',
      label: 'Light Channel',
      startProgress: 0.64,
      endProgress: 0.84,
      phase: 'climax',
      summary: 'A gentle corridor sequence showcases authored lane movement without punishing density.',
      spawnRateMultiplier: 1.16,
      hazardEvents: [{ type: 'rock-corridor', cadenceMs: 2050, corridorWidth: 250, laneCount: 1, damage: 1, intensity: 0.5 }],
      musicIntensity: 0.72,
    },
    {
      id: 'slipstream-release',
      label: 'Blue Quiet',
      startProgress: 0.84,
      endProgress: 1,
      phase: 'intro',
      summary: 'Pressure fades so players can process and prepare for deeper space.',
      spawnRateMultiplier: 0.82,
      asteroidInterval: 5600,
      musicIntensity: 0.38,
    },
  ],
  music: createSignatureMusic({
    cueName: 'Slipstream Anthem',
    bossCueName: 'Slipstream Anthem: Overdrive',
    mood: 'bright launch confidence with exploratory energy',
    tempoFeel: 'steady ignition pulse',
    style: 'glassy arcade synth with elastic bass and orbital shimmer',
    intensity: 'low-medium',
    shifts: ['Debris ribbon adds urgency through denser accents and wider stereo motion.'],
    tempo: 92,
    rootHz: 146.83,
    patternRoot: 0,
    bassPattern: bassPatterns.syncopatedBounce,
    pulsePattern: arpeggiatorPatterns.flowing,
    leadPattern: arpeggiatorPatterns.wideLeap,
    bossPulsePattern: arpeggiatorPatterns.drivingPulse,
    bossLeadPattern: arpeggiatorPatterns.forwardMomentum,
    intent: {
      deterministicSeed: 'asteroid-belt-alpha-slipstream-anthem',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'ionian',
        chordProgressionTags: ['bright-pedal', 'launch-ostinato'],
        rhythmicFeel: 'syncopated glide',
        energyProfile: { baseline: 0.34, peak: 0.72, curve: 'build-release' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 5, barsDuration: 1, quality: 'major' },
            { degree: 6, barsDuration: 1, quality: 'minor' },
            { degree: 4, barsDuration: 1, quality: 'major' },
          ],
        },
      },
      boss: {
        mode: 'mixolydian',
        chordProgressionTags: ['dominant-drive', 'open-fifth-push'],
        rhythmicFeel: 'driving pursuit pulse',
        energyProfile: { baseline: 0.62, peak: 0.9, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
            { degree: 4, barsDuration: 1, quality: 'major' },
            { degree: 5, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
    },
  }),
};
