import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../music';
import { createSignatureMusic } from './reimaginedMusic';

export const ASTEROID_BELT_ALPHA_LEVEL: LevelConfig = {
  name: 'Aurora Threshold',
  planetName: 'Lumen Gate',
  destination: 'Aurora gate corridor above the luminous Lumen Gate',
  visualTheme: 'Teal-violet aurora curtains over a calm cobalt void with glassy debris silhouettes.',
  coreGameplayIdea: 'A gentle lane-reading opener where diver entrances and clean telegraphs build confidence.',
  pacingSummary: 'Warm-up scouts, diver showpiece entrances, one gentle debris-surge stretch, then a calm release.',
  enemyCompositionSummary: 'Scouts fill the lanes, fighters test spacing, and divers debut their dive-bomb entrances.',
  hazardSummary: 'One gentle debris-surge stretch; otherwise clear skies.',
  bossConcept: 'No boss in this opener; the aurora runway itself is the tutorial exam.',
  difficultyRole: 'Onboarding level with strong readability and confidence building.',
  journeyNote: 'Pilots ride a luminous aurora current toward Lumen Gate, more overture than warzone.',
  bgColor: '#040d14',
  accentColor: 0x6af6d8,
  nebulaColor: 0x1c4a5c,
  nebulaAlpha: 0.16,
  colorGrade: { brightness: 0.1, contrast: 1.05, saturation: 1.1 },
  planetPalette: [0x2f8f7a, 0x9ff5e2],
  enemies: [
    { type: 'scout', weight: 60 },
    { type: 'fighter', weight: 25 },
    { type: 'diver', weight: 15 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.0,
  levelDistance: 11000,
  hasBoss: false,
  boss: null,
  bossTriggerProgress: 0.82,
  asteroidInterval: 4700,
  sections: [
    {
      id: 'slipstream-entry',
      label: 'Launch Corridor',
      startProgress: 0,
      endProgress: 0.2,
      phase: 'intro',
      summary: 'Gentle scout arrivals open wide lanes so pilots read the aurora current with confidence.',
      musicIntensity: 0.26,
      tensionArc: 'constant',
      vatTarget: { valence: 0.5, arousal: 0.34, tension: 0.22 },
    },
    {
      id: 'slipstream-debris-ribbon',
      label: 'Debris Ribbon',
      startProgress: 0.2,
      endProgress: 0.44,
      phase: 'build',
      summary: 'One gentle debris-surge stretch teaches hazard telegraphs while divers rehearse their entrances.',
      asteroidInterval: 3800,
      hazardEvents: [{ type: 'debris-surge', cadenceMs: 2350, intensity: 0.33 }],
      waves: [
        {
          id: 'l1-diver-column-intro',
          atMs: 4200,
          formation: 'column',
          type: 'diver',
          count: 2,
          lane: 2,
          telegraph: 'none',
          bonusOnClearMs: 4000,
          bonusWave: { type: 'scout', count: 3 },
          notes: 'First diver entrance rehearses the lane read; clearing inside 4s earns a scout popcorn bonus.',
        },
      ],
      musicIntensity: 0.46,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: 0.45, arousal: 0.48, tension: 0.4 },
    },
    {
      id: 'slipstream-prism-cross',
      label: 'Aurora Crossfire',
      startProgress: 0.44,
      endProgress: 0.64,
      phase: 'hazard',
      summary: 'Mirrored aurora flares frame clean lanes for side reading; a relief beat waits mid-crossing.',
      encounterSizeOverride: { min: 2, max: 2 },
      hazardEvents: [{ type: 'ring-crossfire', cadenceMs: 2000, intensity: 0.44 }],
      recoveryDrops: [
        {
          id: 'l1-health-mid',
          triggerProgress: 0.5,
          type: 'health',
          lane: 'center',
          notes: 'Relief beat: a breather pickup that lets pilots stabilize mid-crossfire.',
        },
      ],
      musicIntensity: 0.6,
      tensionArc: 'waves',
      vatTarget: { valence: 0.32, arousal: 0.62, tension: 0.58 },
    },
    {
      id: 'slipstream-canyon-lite',
      label: 'Aurora Showpiece',
      startProgress: 0.64,
      endProgress: 0.84,
      phase: 'climax',
      summary: 'Diver entrances take center stage in a showpiece climb built on clean telegraphs and confidence.',
      spawnRateMultiplier: 1.14,
      waves: [
        {
          id: 'l1-diver-vee-showpiece',
          atMs: 2600,
          formation: 'vee',
          type: 'diver',
          count: 3,
          lane: 3,
          telegraph: 'warning',
          notes: 'The diver showpiece: a warned vee entrance that assembles before the dive-bomb.',
        },
        {
          id: 'l1-diver-column-echo',
          atMs: 9800,
          formation: 'column',
          type: 'diver',
          count: 2,
          lane: 5,
          telegraph: 'none',
          notes: 'A quiet column echo keeps the showpiece moving without raising threat.',
        },
      ],
      musicIntensity: 0.72,
      tensionArc: 'buildRelease',
      vatTarget: { valence: 0.26, arousal: 0.72, tension: 0.7 },
    },
    {
      id: 'slipstream-release',
      label: 'Blue Quiet',
      startProgress: 0.84,
      endProgress: 1,
      phase: 'intro',
      summary: 'The aurora eases into a gentle release so pilots can breathe before deeper space.',
      spawnRateMultiplier: 0.78,
      asteroidInterval: 5600,
      musicIntensity: 0.34,
      tensionArc: 'constant',
      vatTarget: { valence: 0.58, arousal: 0.26, tension: 0.18 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Aurora Overture',
    bossCueName: 'Aurora Overture: Skyfire',
    mood: 'bright overture confidence with glassy aurora shimmer',
    tempoFeel: 'lifting overture pulse',
    style: 'glassy synth overture with elastic bass and aurora shimmer',
    intensity: 'low-medium',
    shifts: ['Debris surge adds urgency through denser accents and wider stereo motion.'],
    tempo: 96,
    rootHz: 146.83,
    patternRoot: 0,
    bassPattern: bassPatterns.syncopatedBounce,
    pulsePattern: arpeggiatorPatterns.flowing,
    leadPattern: arpeggiatorPatterns.wideLeap,
    bossPulsePattern: arpeggiatorPatterns.drivingPulse,
    bossLeadPattern: arpeggiatorPatterns.forwardMomentum,
    intent: {
      deterministicSeed: 'aurora-threshold-lumen-overture',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'ionian',
        chordProgressionTags: ['bright-pedal', 'launch-ostinato'],
        rhythmicFeel: 'syncopated glide',
        energyProfile: { baseline: 0.34, peak: 0.72, curve: 'build-release' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 5, barsDuration: 1, quality: 'major' },
            { degree: 6, barsDuration: 1, quality: 'minor' },
            { degree: 4, barsDuration: 1, quality: 'major' },
          ],
        },
      },
      boss: {
        mode: 'mixolydian',
        chordProgressionTags: ['dominant-drive', 'open-fifth-push'],
        rhythmicFeel: 'driving pursuit pulse',
        energyProfile: { baseline: 0.62, peak: 0.9, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
            { degree: 4, barsDuration: 1, quality: 'major' },
            { degree: 5, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
    },
  }),
};
