import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets, arpeggiatorPatterns, bassPatterns } from '../musicHelpers';

export const CROWN_OF_RINGS_LEVEL: LevelConfig = {
  name: 'Crown of Rings',
  planetName: 'Astraea IX',
  destination: 'The ring lanes of Astraea IX',
  visualTheme: 'Gold-violet ring dust, glinting shards, and planetary light bands.',
  coreGameplayIdea: 'Orbital hazards create moving lanes while enemy interceptors capitalize on forced routes.',
  pacingSummary: 'Wide scenic opening, then increasingly organized ring hazards, then a rotating artillery boss.',
  enemyCompositionSummary: 'Fighters and gunships dominate with bombers anchoring lane denial.',
  hazardSummary: 'Ring-crossfire, orbital debris sweeps, and mine pockets.',
  bossConcept: 'A ring shepherd artillery rig that rotates attack lanes around the player.',
  difficultyRole: 'Tests route planning and lane prediction under higher speed.',
  journeyNote: 'The player leaves cloud cover and skims the majestic but militarized rings of a gas giant.',
  bgColor: '#130d05',
  accentColor: 0xffd26a,
  nebulaColor: 0x775321,
  nebulaAlpha: 0.1,
  colorGrade: { brightness: 0.05, contrast: 1.14, saturation: 1.18 },
  planetPalette: [0xa97428, 0xe1b45b],
  enemies: [
    { type: 'scout', weight: 10 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 18 },
    { type: 'swarm', weight: 12 },
    { type: 'gunship', weight: 30 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.12,
  levelDistance: 13800,
  hasBoss: true,
  boss: {
    name: 'Ring Shepherd',
    maxHp: 98,
    phase1Cooldown: 840,
    phase2Cooldown: 390,
    phase2MoveSpeed: 228,
    attackStyle: 'bulwark',
    phase1SpreadShotCount: 8,
    phase1SpreadArcDegrees: 70,
    phase1BulletSpeedScale: 1.05,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 116,
    phase2BulletSpeedScale: 1.1,
  },
  bossTriggerProgress: 0.64,
  asteroidInterval: 3600,
  sections: [
    {
      id: 'rings-open',
      label: 'Outer Rings',
      startProgress: 0,
      endProgress: 0.22,
      phase: 'intro',
      summary: 'A broad scenic opening introduces the ring lanes and dust flow.',
      enemyFocus: [
        { type: 'scout', weight: 30 },
        { type: 'fighter', weight: 55 },
        { type: 'gunship', weight: 15 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.86,
      musicIntensity: 0.4,
    },
    {
      id: 'rings-crossfire',
      label: 'Orbital Crossfire',
      startProgress: 0.22,
      endProgress: 0.64,
      phase: 'hazard',
      summary: 'Dust lanes and interceptors combine to pressure prediction-based movement.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 18 },
        { type: 'swarm', weight: 12 },
        { type: 'gunship', weight: 36 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 2.08,
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 2100, intensity: 0.74 },
        { type: 'minefield', cadenceMs: 3400, intensity: 0.42 },
      ],
      musicIntensity: 0.86,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Orbital Crown',
      mood: 'majestic focus with ethereal grace',
      tempoFeel: 'ceremonial orbit with forward motion',
      musicalStyle: 'regal synth fanfare softened by ring-dust shimmer and elegant pulse ostinato',
      intensity: 'medium-high with ambient swells',
      shiftMoments: ['Crossfire sections add more pulse interlock.', 'Boss variation broadens the fanfare and adds brighter ring-dust texture.'],
      bossCueName: 'Orbital Crown: Ring Shepherd',
    },
    {
      tempo: 104,
      rootHz: 130.81,
      stepsPerBeat: 4,
      masterGain: 0.9,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        stereo: { ...trackExpressionPresets.expansiveSpace.stereo, width: 0.38, rateHz: 0.08 },
        accent: { amount: 0.08, patternBias: 0.16, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sine',
        pattern: bassPatterns.rootFifth(0),
        gain: 0.14,
        durationSteps: 4,
        filterHz: 950,
        expression: {
          ...layerExpressionPresets.longPad,
          ...layerExpressionPresets.wideSpace,
          accent: { ...layerExpressionPresets.breathPulse.accent, emphasisSteps: [0, 4, 8, 12] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.upDownTriad(12),
        gain: 0.038,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1800,
        expression: {
          ...layerExpressionPresets.softPluck,
          ...layerExpressionPresets.orbit,
          accent: { amount: 0.1, patternBias: 0.18, emphasisSteps: [0, 2, 5, 8, 12] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.cascade(24),
        gain: 0.034,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1600,
        expression: {
          ...layerExpressionPresets.slowSwell,
          ...layerExpressionPresets.wideSpace,
          ...layerExpressionPresets.gentleVibrato,
        },
      },
      noise: {
        pattern: [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0],
        gain: 0.012,
        filterHz: 1700,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.dreamyDrift,
          stereo: { ...noiseExpressionPresets.dreamyDrift.stereo, width: 0.35, rateHz: 0.09 },
        },
      },
    },
    {
      tempo: 110,
      masterGain: 0.96,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 220, rateHz: 0.85 },
        accent: { amount: 0.14, patternBias: 0.28, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { gain: 0.15, filterHz: 1050 },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.flowing(12),
        gain: 0.048,
      },
      lead: { waveform: 'sine', gain: 0.04, filterHz: 1750 },
      noise: {
        gain: 0.015,
        filterHz: 2200,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.1, patternBias: 0.18, emphasisSteps: [2, 6, 10, 14] },
        },
      },
    }
  ),
};
