import type { LevelConfig } from '../types';
import { createMusicProfile } from '../musicHelpers';

export const CROWN_OF_RINGS_LEVEL: LevelConfig = {
  name: 'Crown of Rings',
  planetName: 'Astraea IX',
  destination: 'The ring lanes of Astraea IX',
  visualTheme: 'Gold-violet ring dust, glinting shards, and planetary light bands.',
  coreGameplayIdea: 'Orbital hazards create moving lanes while enemy interceptors capitalize on forced routes.',
  pacingSummary: 'Wide scenic opening, then increasingly organized ring hazards, then a rotating artillery boss.',
  enemyCompositionSummary: 'Fighters and gunships dominate with bombers anchoring lane denial.',
  hazardSummary: 'Ring-crossfire, orbital debris sweeps, and mine pockets.',
  bossConcept: 'A ring shepherd artillery rig that rotates attack lanes around the player.',
  difficultyRole: 'Tests route planning and lane prediction under higher speed.',
  journeyNote: 'The player leaves cloud cover and skims the majestic but militarized rings of a gas giant.',
  bgColor: '#130d05',
  accentColor: 0xffd26a,
  nebulaColor: 0x775321,
  nebulaAlpha: 0.1,
  colorGrade: { brightness: 0.05, contrast: 1.14, saturation: 1.18 },
  planetPalette: [0xa97428, 0xe1b45b],
  enemies: [
    { type: 'scout', weight: 10 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 18 },
    { type: 'swarm', weight: 12 },
    { type: 'gunship', weight: 30 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.12,
  levelDistance: 13800,
  hasBoss: true,
  boss: {
    name: 'Ring Shepherd',
    maxHp: 98,
    phase1Cooldown: 840,
    phase2Cooldown: 390,
    phase2MoveSpeed: 228,
    attackStyle: 'bulwark',
    phase1SpreadShotCount: 8,
    phase1SpreadArcDegrees: 70,
    phase1BulletSpeedScale: 1.05,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 116,
    phase2BulletSpeedScale: 1.1,
  },
  bossTriggerProgress: 0.64,
  asteroidInterval: 3600,
  sections: [
    {
      id: 'rings-open',
      label: 'Outer Rings',
      startProgress: 0,
      endProgress: 0.22,
      phase: 'intro',
      summary: 'A broad scenic opening introduces the ring lanes and dust flow.',
      enemyFocus: [
        { type: 'scout', weight: 30 },
        { type: 'fighter', weight: 55 },
        { type: 'gunship', weight: 15 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.86,
      musicIntensity: 0.4,
    },
    {
      id: 'rings-crossfire',
      label: 'Orbital Crossfire',
      startProgress: 0.22,
      endProgress: 0.64,
      phase: 'hazard',
      summary: 'Dust lanes and interceptors combine to pressure prediction-based movement.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 18 },
        { type: 'swarm', weight: 12 },
        { type: 'gunship', weight: 36 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 2.08,
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 2100, intensity: 0.74 },
        { type: 'minefield', cadenceMs: 3400, intensity: 0.42 },
      ],
      musicIntensity: 0.86,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Orbital Crown',
      mood: 'majestic tension',
      tempoFeel: 'propulsive with a ceremonial pulse',
      musicalStyle: 'bright synth brass lead over urgent arcade percussion simulation',
      intensity: 'high',
      shiftMoments: ['Crossfire sections add extra pulse density.', 'Boss variation sharpens the lead into artillery fanfares.'],
      bossCueName: 'Orbital Crown: Ring Shepherd',
    },
    {
      tempo: 132,
      rootHz: 130.81,
      stepsPerBeat: 4,
      masterGain: 1.03,
      bass: {
        waveform: 'triangle',
        pattern: [0, null, 0, null, 5, null, 7, null, 10, null, 7, null, 12, null, 10, null],
        gain: 0.18,
        durationSteps: 2,
        filterHz: 1000,
      },
      pulse: {
        waveform: 'square',
        pattern: [12, null, 15, 12, null, 15, null, 19, 20, null, 19, null, 15, null, 12, null],
        gain: 0.058,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 2300,
      },
      lead: {
        waveform: 'sawtooth',
        pattern: [24, null, null, 22, 24, null, null, 27, 29, null, null, 27, 24, null, 22, null],
        gain: 0.048,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1800,
      },
      noise: {
        pattern: [1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0],
        gain: 0.019,
        filterHz: 2600,
        durationSteps: 1,
      },
    },
    {
      tempo: 144,
      masterGain: 1.12,
      bass: { gain: 0.2 },
      pulse: { gain: 0.066 },
      lead: { gain: 0.058 },
      noise: { gain: 0.024, filterHz: 3000 },
    }
  ),
};
