import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const CROWN_OF_RINGS_LEVEL: LevelConfig = {
  name: 'Halo Cartography',
  planetName: 'Astraea Atlas',
  destination: 'Orbital charting lattice in Astraea’s ring crown',
  visualTheme: 'Gold-violet arcs, disciplined ring geometry, and ceremonial light bands.',
  coreGameplayIdea: 'A predictive orbital-cadence stage where players solve repeating geometry before tempo spikes.',
  pacingSummary: 'Scenic setup, mapped ring cycles, artillery cadence spike, then bulwark duel.',
  enemyCompositionSummary: 'Fighters and gunships dominate; bombers gate movement choices.',
  hazardSummary: 'Mapped ring cycles, orbital disruption pulls, and artillery cadence bursts with minimal randomness.',
  bossConcept: 'Orbital Cantor rotates bulwark patterns and tests sustained lane memory.',
  difficultyRole: 'High-speed pattern recognition milestone before final stretch.',
  journeyNote: 'The route resembles sacred geometry where every arc predicts the next threat.',
  bgColor: '#140f09',
  accentColor: 0xffd266,
  nebulaColor: 0x5f3f1f,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.07, contrast: 1.16, saturation: 1.02 },
  planetPalette: [0xba8f47, 0xffdf8f],
  enemies: [
    { type: 'fighter', weight: 34 },
    { type: 'bomber', weight: 20 },
    { type: 'swarm', weight: 14 },
    { type: 'gunship', weight: 32 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2,
  levelDistance: 19400,
  hasBoss: true,
  boss: {
    name: 'Orbital Cantor',
    maxHp: 4400,
    phase1Cooldown: 810,
    phase2Cooldown: 390,
    phase2MoveSpeed: 234,
    attackStyle: 'bulwark',
    phase1SpreadShotCount: 8,
    phase1SpreadArcDegrees: 74,
    phase1BulletSpeedScale: 1.05,
    phase2SpiralShotCount: 6,
    phase2SpiralTurnRate: 118,
    phase2BulletSpeedScale: 1.11,
  },
  bossTriggerProgress: 0.63,
  asteroidInterval: 3150,
  sections: [
    {
      id: 'halo-approach',
      label: 'Atlas Entry',
      startProgress: 0,
      endProgress: 0.14,
      phase: 'intro',
      summary: 'Readable opening with generous ring telegraph windows.',
      musicIntensity: 0.46,
      tensionArc: 'constant',
      vatTarget: { valence: -0.1, arousal: 0.5, tension: 0.46 },
    },
    {
      id: 'halo-sweeps',
      label: 'Mapped Sweeps',
      startProgress: 0.14,
      endProgress: 0.34,
      phase: 'build',
      summary: 'Mapped orbital cycles reward prediction by repeating geometric lane calls.',
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 1780, intensity: 0.67 },
        { type: 'debris-surge', cadenceMs: 2740, intensity: 0.36 },
      ],
      musicIntensity: 0.64,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.16, arousal: 0.64, tension: 0.62 },
    },
    {
      id: 'halo-disrupt',
      label: 'Disruption Nodes',
      startProgress: 0.34,
      endProgress: 0.5,
      phase: 'hazard',
      summary: 'Disruption nodes invert the mapped rhythm with alternating pull and sweep beats.',
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 2040, intensity: 0.58 },
        { type: 'gravity-well', cadenceMs: 2140, intensity: 0.62 },
      ],
      musicIntensity: 0.8,
      tensionArc: 'waves',
      vatTarget: { valence: -0.22, arousal: 0.76, tension: 0.74 },
    },
    {
      id: 'halo-artillery',
      label: 'Artillery Halo',
      startProgress: 0.5,
      endProgress: 0.61,
      phase: 'climax',
      summary: 'Artillery cadence spike compresses route calls into high-speed, still-readable orbital repeats.',
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 2.04,
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 1560, intensity: 0.76 },
        { type: 'gravity-well', cadenceMs: 1880, intensity: 0.52 },
        { type: 'debris-surge', cadenceMs: 2200, intensity: 0.56 },
      ],
      musicIntensity: 0.94,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.28, arousal: 0.88, tension: 0.88 },
    },
    {
      id: 'halo-cantor',
      label: 'Cantor Gate',
      startProgress: 0.61,
      endProgress: 0.63,
      phase: 'boss-approach',
      summary: 'Ceremonial warning beat before artillery sovereign appears.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 4900,
      musicIntensity: 0.86,
      tensionArc: 'constant',
      vatTarget: { valence: -0.08, arousal: 0.48, tension: 0.54 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Crown Geometry',
    bossCueName: 'Crown Geometry: Cantor Litany',
    mood: 'regal urgency with disciplined force',
    tempoFeel: 'measured pulse accelerating into barrage',
    style: 'bright harmonic stabs over strict percussive drive',
    intensity: 'very high',
    shifts: ['Artillery halo pushes denser accents and broader stereo spread for lane drama.'],
    tempo: 112,
    rootHz: 98,
    patternRoot: 7,
    bassPattern: bassPatterns.pushRhythm,
    pulsePattern: arpeggiatorPatterns.quartalCascade,
    leadPattern: arpeggiatorPatterns.octaveDance,
    bossBassPattern: bassPatterns.finalBossOstinato,
    bossPulsePattern: arpeggiatorPatterns.finalBossIntensity,
    bossLeadPattern: arpeggiatorPatterns.tensionMaximum,
    bossTempo: 124,
    intent: {
      deterministicSeed: 'crown-of-rings-crown-geometry',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'mixolydian',
        chordProgressionTags: ['quartal-fanfare', 'ceremonial-dominant-loop'],
        rhythmicFeel: 'measured barrage pulse',
        energyProfile: { baseline: 0.56, peak: 0.95, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
            { degree: 4, barsDuration: 1, quality: 'major' },
            { degree: 5, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'phrygian-dominant',
        chordProgressionTags: ['sovereign-ostinato', 'tritone-declaration'],
        rhythmicFeel: 'artillery surge cadence',
        energyProfile: { baseline: 0.74, peak: 0.99, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'major' },
          ],
        },
      },
    },
  }),
};
