import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets, arpeggiatorPatterns, bassPatterns } from '../musicHelpers';

export const DEEP_SPACE_INFERNO_LEVEL: LevelConfig = {
  name: 'Deep Space Inferno',
  planetName: 'Betelgeuse Gate',
  destination: 'The unstable gate above Betelgeuse',
  visualTheme: 'Deep crimson void, hot pink highlights, and volatile solar glow.',
  coreGameplayIdea: 'Long-form endurance where threat density climbs almost continuously.',
  pacingSummary: 'Sustained pressure, almost no safe pauses, and a brutal boss finish.',
  enemyCompositionSummary: 'All current enemy families at meaningful density.',
  hazardSummary: 'Heavy asteroid cadence and layered projectile pressure.',
  bossConcept: 'A maelstrom core that turns endurance into an aggressive bullet exam.',
  difficultyRole: 'Current endgame benchmark before the new expansion arc begins.',
  journeyNote: 'The player survives the known frontier and enters stranger outer regions.',
  bgColor: '#18010c',
  accentColor: 0xff4488,
  nebulaColor: 0x661133,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.02, contrast: 1.18, saturation: 1.32 },
  planetPalette: [0x884444, 0xaa6666],
  enemies: [
    { type: 'scout', weight: 15 },
    { type: 'fighter', weight: 25 },
    { type: 'bomber', weight: 20 },
    { type: 'swarm', weight: 20 },
    { type: 'gunship', weight: 20 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.0,
  levelDistance: 17000,
  hasBoss: true,
  boss: {
    name: 'Inferno Harbinger',
    maxHp: 80,
    phase1Cooldown: 850,
    phase2Cooldown: 425,
    phase2MoveSpeed: 205,
    attackStyle: 'maelstrom',
    phase1SpreadShotCount: 9,
    phase1SpreadArcDegrees: 70,
    phase1BulletSpeedScale: 1,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 104,
    phase2BulletSpeedScale: 1.05,
  },
  bossTriggerProgress: 0.62,
  asteroidInterval: 3000,
  sections: [
    {
      id: 'inferno-entry',
      label: 'Heat Threshold',
      startProgress: 0,
      endProgress: 0.12,
      phase: 'intro',
      summary: 'Solar winds rise gently while small enemy patrols scout the periphery.',
      enemyFocus: [
        { type: 'scout', weight: 50 },
        { type: 'fighter', weight: 30 },
        { type: 'swarm', weight: 20 },
      ],
      encounterSizeOverride: { min: 1, max: 2 },
      spawnRateMultiplier: 1.2,
      musicIntensity: 0.4,
    },
    {
      id: 'inferno-burn',
      label: 'Thermal Currents',
      startProgress: 0.12,
      endProgress: 0.28,
      phase: 'build',
      summary: 'Heat intensifies as bomber wings approach and asteroid streams thicken.',
      enemyFocus: [
        { type: 'fighter', weight: 40 },
        { type: 'bomber', weight: 25 },
        { type: 'scout', weight: 20 },
        { type: 'swarm', weight: 15 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.5,
      asteroidInterval: 2600,
      hazardEvents: [{ type: 'ambient-asteroids', cadenceMs: 2200, intensity: 0.5 }],
      musicIntensity: 0.6,
    },
    {
      id: 'inferno-chromatic',
      label: 'Chromatic Flare',
      startProgress: 0.28,
      endProgress: 0.44,
      phase: 'hazard',
      summary: 'The chromatic storm flares with particle bombardment and enemy escorts.',
      enemyFocus: [
        { type: 'fighter', weight: 35 },
        { type: 'bomber', weight: 30 },
        { type: 'swarm', weight: 20 },
        { type: 'scout', weight: 15 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 1.7,
      asteroidInterval: 2400,
      hazardEvents: [
        { type: 'ambient-asteroids', cadenceMs: 1800, intensity: 0.65 },
        { type: 'debris-surge', cadenceMs: 2400, intensity: 0.5 },
      ],
      musicIntensity: 0.8,
    },
    {
      id: 'inferno-furnace',
      label: 'The Furnace',
      startProgress: 0.44,
      endProgress: 0.58,
      phase: 'climax',
      summary: 'Maximum heat. Gunships anchor positions while swarms flood the gaps.',
      enemyFocus: [
        { type: 'fighter', weight: 30 },
        { type: 'bomber', weight: 25 },
        { type: 'gunship', weight: 25 },
        { type: 'swarm', weight: 20 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 1.9,
      asteroidInterval: 2200,
      hazardEvents: [
        { type: 'ambient-asteroids', cadenceMs: 1600, intensity: 0.8 },
        { type: 'energy-storm', cadenceMs: 2000, intensity: 0.6 },
      ],
      musicIntensity: 0.92,
    },
    {
      id: 'inferno-approach-boss',
      label: 'Nuclear Core',
      startProgress: 0.58,
      endProgress: 0.62,
      phase: 'boss-approach',
      summary: 'The heat reaches impossible levels as the core guardian emerges.',
      musicIntensity: 0.98,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Solar Burn',
      mood: 'heat-haze determination with maximum intensity drive',
      tempoFeel: 'relentless burning stride with urgent chromatic tension',
      musicalStyle: 'molten bass drive with tension chromatics and urgent dash patterns',
      intensity: 'very high with aggressive forward momentum',
      shiftMoments: ['Overload sections ignite with chromatic tension patterns.', 'Boss cue explodes with maximum intensity through urgent dash and power chord dominance.'],
      bossCueName: 'Solar Burn: Harbinger',
    },
    {
      tempo: 112,
      rootHz: 123.47,
      stepsPerBeat: 4,
      masterGain: 0.96,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        stereo: { ...trackExpressionPresets.expansiveSpace.stereo, width: 0.46, rateHz: 0.16 },
        accent: { amount: 0.16, patternBias: 0.3, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: {
        waveform: 'triangle',
        pattern: bassPatterns.powerChordBass(0),
        gain: 0.17,
        durationSteps: 2,
        filterHz: 1200,
        expression: {
          ...layerExpressionPresets.longPad,
          ...layerExpressionPresets.wideSpace,
          accent: { ...layerExpressionPresets.breathPulse.accent, emphasisSteps: [0, 4, 8, 12] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.tensionChromatic(12),
        gain: 0.048,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 2100,
        expression: {
          ...layerExpressionPresets.pluck,
          ...layerExpressionPresets.ambientDrift,
          accent: { amount: 0.17, patternBias: 0.32, emphasisSteps: [0, 2, 4, 8, 10, 12, 14] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.urgentDash(24),
        gain: 0.04,
        durationSteps: 2,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.swell,
          ...layerExpressionPresets.vibrato,
          stereo: { width: 0.52, rateHz: 0.18 },
        },
      },
      noise: {
        pattern: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
        gain: 0.018,
        filterHz: 2200,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.12, patternBias: 0.22, emphasisSteps: [1, 3, 5, 7, 9, 11, 13, 15] },
        },
      },
    },
    {
      tempo: 120,
      masterGain: 1.05,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 340, rateHz: 1.25 },
        accent: { amount: 0.24, patternBias: 0.48, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { gain: 0.2, filterHz: 1350 },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.urgentDash(12),
        gain: 0.062,
      },
      lead: { waveform: 'sine', gain: 0.05, filterHz: 1800 },
      noise: {
        gain: 0.024,
        filterHz: 2800,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.15, patternBias: 0.28, emphasisSteps: [2, 4, 6, 8, 10, 12, 14] },
        },
      },
    }
  ),
};
