import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../music';
import { createSignatureMusic } from './reimaginedMusic';

export const DEEP_SPACE_INFERNO_LEVEL: LevelConfig = {
  name: 'Shatter Reef',
  planetName: 'Korra Vale',
  destination: 'Coral shatterfields of Korra Vale',
  visualTheme: 'Coral-pink reef fans over a violet abyss with bubble sparkles.',
  coreGameplayIdea: 'Splitters multiply on death; target priority becomes the mid-campaign exam.',
  pacingSummary: 'A nebula-ambush remix and splitter packs build toward the Reef Stalker hunt.',
  enemyCompositionSummary: 'Fighters and gunships escort splitter broods while bombers break tempo.',
  hazardSummary: 'Nebula ambush windows remixed with reef debris.',
  bossConcept: 'Reef Stalker hunts with pursuit patterns through the coral lanes.',
  difficultyRole: 'Mid-campaign exam on the ramp.',
  journeyNote: 'The reef shatters beautifully; every kill multiplies the danger.',
  bgColor: '#0c0714',
  accentColor: 0xff7ab8,
  nebulaColor: 0x3d1440,
  nebulaAlpha: 0.13,
  colorGrade: { brightness: 0.05, contrast: 1.12, saturation: 1.1 },
  planetPalette: [0x8f2a5c, 0x7af5d8],
  enemies: [
    { type: 'fighter', weight: 25 },
    { type: 'splitter', weight: 25 },
    { type: 'bomber', weight: 20 },
    { type: 'gunship', weight: 30 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 1.75,
  levelDistance: 17500,
  hasBoss: true,
  boss: {
    name: 'Reef Stalker',
    maxHp: 1850,
    phase1Cooldown: 900,
    phase2Cooldown: 460,
    phase2MoveSpeed: 210,
    phaseTransitionPauseMs: 280,
    attackStyle: 'pursuit',
    phase1SpreadShotCount: 5,
    phase1SpreadArcDegrees: 52,
    phase1BulletSpeedScale: 1.0,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 100,
    phase2BulletSpeedScale: 1.06,
    guardCapacity: 30,
    guardDecayDelayMs: 1200,
    guardDecayPerSecond: 10,
    guardBreakDurationMs: 1800,
  },
  bossAddWaves: true,
  bossTriggerProgress: 0.7,
  asteroidInterval: 3400,
  sections: [
    {
      id: 'reef-shallows-run',
      label: 'Shallows Run',
      startProgress: 0,
      endProgress: 0.14,
      phase: 'intro',
      summary: 'Coral lanes open gently; early fighter pairs teach the reef current before the splitters arrive.',
      musicIntensity: 0.44,
      tensionArc: 'constant',
      vatTarget: { valence: -0.1, arousal: 0.48, tension: 0.44 },
    },
    {
      id: 'reef-brood-debut',
      label: 'Brood Debut',
      startProgress: 0.14,
      endProgress: 0.33,
      phase: 'build',
      summary: 'The first splitter broods warp in behind warnings; every kill can multiply into swarmlings.',
      enemyFocus: [
        { type: 'splitter', weight: 40 },
        { type: 'fighter', weight: 35 },
        { type: 'bomber', weight: 25 },
      ],
      waves: [
        {
          id: 'splitter-brood-debut',
          atMs: 7300,
          formation: 'line',
          type: 'splitter',
          count: 3,
          lane: 3,
          telegraph: 'warning',
          bonusOnClearMs: 4000,
          bonusWave: { type: 'swarm', count: 4 },
          notes:
            'Splitter debut: a telegraphed center-lane line that multiplies into swarmlings; fast clears earn a bonus popcorn wave.',
        },
      ],
      hazardEvents: [
        {
          type: 'nebula-ambush',
          cadenceMs: 2400,
          intensity: 0.6,
          notes: 'Ambush Anticipation build: the first nebula-ambush of the remix stays readable inside the reef haze.',
        },
        { type: 'debris-surge', cadenceMs: 3100, intensity: 0.4 },
      ],
      musicIntensity: 0.6,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.16, arousal: 0.62, tension: 0.58 },
    },
    {
      id: 'reef-ambush-current',
      label: 'Ambush Current',
      startProgress: 0.33,
      endProgress: 0.51,
      phase: 'hazard',
      summary: 'The nebula-ambush remix returns harder, hiding bomber runs that punish poor target priority.',
      waves: [
        {
          id: 'splitter-ring-remix',
          atMs: 10900,
          formation: 'ring',
          type: 'splitter',
          count: 3,
          lane: 2,
          telegraph: 'warning',
          notes: 'A splitter ring off the left lanes multiplies unless the player picks a priority arc early.',
        },
      ],
      recoveryDrops: [
        {
          id: 'reef-relief-health',
          triggerProgress: 0.66,
          type: 'health',
          lane: 'center',
          notes: 'Relief beat after the ambush remix peak, stabilizing hull before the stalker trail.',
        },
      ],
      hazardEvents: [
        { type: 'nebula-ambush', cadenceMs: 2200, intensity: 0.72 },
        { type: 'ring-crossfire', cadenceMs: 2900, intensity: 0.5 },
      ],
      musicIntensity: 0.76,
      tensionArc: 'waves',
      vatTarget: { valence: -0.22, arousal: 0.74, tension: 0.7 },
    },
    {
      id: 'reef-stalker-trail',
      label: 'Stalker Trail',
      startProgress: 0.51,
      endProgress: 0.68,
      phase: 'climax',
      summary: 'Gunship escorts crowd the coral lanes; target priority decides the Reef Stalker hunt.',
      encounterSizeOverride: { min: 2, max: 3 },
      signatureWaves: [
        {
          id: 'stalker-priority-check',
          triggerProgress: 0.3,
          enemies: [
            { type: 'splitter', lane: 'left', ace: true },
            { type: 'gunship', lane: 'right' },
          ],
          notes:
            'Lane-reading priority check: the gilded ace splitter lane multiplies if ignored while the gunship lane pressures the route.',
        },
      ],
      waves: [
        {
          id: 'reef-midboss-elite',
          atMs: 10900,
          formation: 'pincer',
          type: 'gunship',
          count: 3,
          aceCount: 1,
          midBossBeat: true,
          telegraph: 'warning',
          notes:
            'Mid-boss elite beat at ~60%: a gunship pincer with banner and warning telegraphs punctuates the mid-campaign exam; the gilded ace lead is the priority read.',
        },
      ],
      hazardEvents: [
        { type: 'nebula-ambush', cadenceMs: 2400, intensity: 0.68 },
        { type: 'debris-surge', cadenceMs: 3400, intensity: 0.55 },
      ],
      musicIntensity: 0.9,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.28, arousal: 0.86, tension: 0.84 },
    },
    {
      id: 'reef-stalker-gate',
      label: 'Stalker Gate',
      startProgress: 0.68,
      endProgress: 0.7,
      phase: 'boss-approach',
      summary: 'The reef stills for a breath as the Reef Stalker picks up the trail.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 5100,
      recoveryDrops: [
        {
          id: 'pre-stalker-shield',
          triggerProgress: 0.4,
          type: 'shield',
          lane: 'center',
          notes: 'Pre-boss Recovery Beat shield stabilizes the run before the pursuit duel.',
        },
      ],
      musicIntensity: 0.8,
      tensionArc: 'constant',
      vatTarget: { valence: -0.08, arousal: 0.46, tension: 0.52 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Reef Break',
    bossCueName: 'Reef Break: Reef Stalker',
    mood: 'restless chase with splintering accents',
    tempoFeel: 'surging hunt pulse',
    style: 'driving coral synth over splintered bass breaks',
    intensity: 'high',
    shifts: ['Reef run pushes bass aggression and brighter harmonic bite.'],
    tempo: 116,
    rootHz: 87.31,
    patternRoot: 0,
    bassPattern: bassPatterns.aggressiveBass,
    pulsePattern: arpeggiatorPatterns.aggressiveAttack,
    leadPattern: arpeggiatorPatterns.urgentDash,
    bossBassPattern: bassPatterns.powerChordBass,
    bossPulsePattern: arpeggiatorPatterns.darkChromatic,
    bossLeadPattern: arpeggiatorPatterns.tensionMaximum,
    bossTempo: 116,
    intent: {
      deterministicSeed: 'shatter-reef-coral-break',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'aeolian',
        chordProgressionTags: ['power-chord-engine', 'molten-pedal'],
        rhythmicFeel: 'heavy stride with ignition bursts',
        energyProfile: { baseline: 0.48, peak: 0.9, curve: 'build-release' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 6, barsDuration: 1, quality: 'major' },
            { degree: 3, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
          ],
        },
      },
      boss: {
        mode: 'phrygian-dominant',
        chordProgressionTags: ['chromatic-burn', 'fifth-stack-surge'],
        rhythmicFeel: 'serrated barrage drive',
        energyProfile: { baseline: 0.72, peak: 0.98, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'major' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'major' },
          ],
        },
      },
    },
  }),
};
