import type { LevelConfig } from '../types';
import { createMusicProfile } from '../musicHelpers';

export const DEEP_SPACE_INFERNO_LEVEL: LevelConfig = {
  name: 'Deep Space Inferno',
  planetName: 'Betelgeuse Gate',
  destination: 'The unstable gate above Betelgeuse',
  visualTheme: 'Deep crimson void, hot pink highlights, and volatile solar glow.',
  coreGameplayIdea: 'Long-form endurance where threat density climbs almost continuously.',
  pacingSummary: 'Sustained pressure, almost no safe pauses, and a brutal boss finish.',
  enemyCompositionSummary: 'All current enemy families at meaningful density.',
  hazardSummary: 'Heavy asteroid cadence and layered projectile pressure.',
  bossConcept: 'A maelstrom core that turns endurance into an aggressive bullet exam.',
  difficultyRole: 'Current endgame benchmark before the new expansion arc begins.',
  journeyNote: 'The player survives the known frontier and enters stranger outer regions.',
  bgColor: '#18010c',
  accentColor: 0xff4488,
  nebulaColor: 0x661133,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.02, contrast: 1.18, saturation: 1.32 },
  planetPalette: [0x884444, 0xaa6666],
  enemies: [
    { type: 'scout', weight: 15 },
    { type: 'fighter', weight: 25 },
    { type: 'bomber', weight: 20 },
    { type: 'swarm', weight: 20 },
    { type: 'gunship', weight: 20 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.0,
  levelDistance: 12000,
  hasBoss: true,
  boss: {
    name: 'Inferno Harbinger',
    maxHp: 80,
    phase1Cooldown: 850,
    phase2Cooldown: 425,
    phase2MoveSpeed: 205,
    attackStyle: 'maelstrom',
    phase1SpreadShotCount: 9,
    phase1SpreadArcDegrees: 70,
    phase1BulletSpeedScale: 1,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 104,
    phase2BulletSpeedScale: 1.05,
  },
  bossTriggerProgress: 0.64,
  asteroidInterval: 3000,
  sections: [
    {
      id: 'inferno-push',
      label: 'Burning Lane',
      startProgress: 0,
      endProgress: 0.34,
      phase: 'build',
      summary: 'The stage starts hot and gets hotter instead of resetting between patterns.',
      musicIntensity: 0.7,
    },
    {
      id: 'inferno-overload',
      label: 'Overload',
      startProgress: 0.34,
      endProgress: 0.64,
      phase: 'climax',
      summary: 'Every enemy type contributes to a sustained gauntlet.',
      asteroidInterval: 2600,
      hazardEvents: [{ type: 'energy-storm', cadenceMs: 1800, intensity: 0.9 }],
      musicIntensity: 0.95,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Solar Redline',
      mood: 'high-pressure determination',
      tempoFeel: 'fast and relentless',
      musicalStyle: 'arcade chase groove with rising lead alarms',
      intensity: 'very high',
      shiftMoments: ['Mid-level overload adds more lead movement.', 'Boss cue becomes almost siren-like.'],
      bossCueName: 'Solar Redline: Harbinger',
    },
    {
      tempo: 148,
      rootHz: 116.54,
      stepsPerBeat: 4,
      masterGain: 1.04,
      bass: {
        waveform: 'sawtooth',
        pattern: [0, null, 3, null, 7, null, 10, null, 12, null, 10, null, 7, null, 3, null],
        gain: 0.19,
        durationSteps: 2,
        filterHz: 1200,
      },
      pulse: {
        waveform: 'square',
        pattern: [12, null, 15, null, 19, null, 15, null, 22, null, 19, null, 17, null, 15, null],
        gain: 0.065,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 2500,
      },
      lead: {
        waveform: 'triangle',
        pattern: [24, null, 22, null, 24, null, 27, null, 29, null, 27, null, 24, null, 22, null],
        gain: 0.055,
        durationSteps: 1,
        octaveShift: 1,
      },
      noise: {
        pattern: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        gain: 0.022,
        filterHz: 2800,
        durationSteps: 1,
      },
    },
    {
      tempo: 160,
      masterGain: 1.14,
      bass: { gain: 0.21 },
      pulse: { gain: 0.072 },
      lead: { waveform: 'sawtooth', gain: 0.065 },
      noise: { gain: 0.028, filterHz: 3200 },
    }
  ),
};
