import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets } from '../musicHelpers';

export const GHOSTLIGHT_VEIL_LEVEL: LevelConfig = {
  name: 'Ghostlight Veil',
  planetName: 'Nacre Reach',
  destination: 'A luminous nebula wall around Nacre Reach',
  visualTheme: 'Pale blue-violet fog, ghostly glows, and low-visibility pockets.',
  coreGameplayIdea: 'Ambush patterns emerge out of fog bands while visibility keeps changing.',
  pacingSummary: 'Slow drift, deceptive quiet, then repeated pincer ambushes.',
  enemyCompositionSummary: 'Swarms and fighters create shape-changing flanks while bombers punish tunnel vision.',
  hazardSummary: 'Nebula ambush zones and erratic mine-like pressure.',
  bossConcept: 'A cloaking manta that disappears into fog and returns with spread formations.',
  difficultyRole: 'Raises information pressure instead of just numbers.',
  journeyNote: 'The path narrows through a beautiful but hostile cloud sea where sensor ghosts lie.',
  bgColor: '#090b1e',
  accentColor: 0xb3a0ff,
  nebulaColor: 0x5a4ec1,
  nebulaAlpha: 0.16,
  colorGrade: { brightness: 0.05, contrast: 1.1, saturation: 1.16 },
  planetPalette: [0x6650aa, 0x9f89da],
  enemies: [
    { type: 'scout', weight: 12 },
    { type: 'fighter', weight: 28 },
    { type: 'bomber', weight: 16 },
    { type: 'swarm', weight: 24 },
    { type: 'gunship', weight: 20 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.04,
  levelDistance: 13200,
  hasBoss: true,
  boss: {
    name: 'Veil Manta',
    maxHp: 90,
    phase1Cooldown: 820,
    phase2Cooldown: 410,
    phase2MoveSpeed: 225,
    attackStyle: 'pursuit',
    phase1SpreadShotCount: 7,
    phase1SpreadArcDegrees: 66,
    phase1BulletSpeedScale: 1.03,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 110,
    phase2BulletSpeedScale: 1.08,
  },
  bossTriggerProgress: 0.66,
  asteroidInterval: 4200,
  sections: [
    {
      id: 'ghostlight-drift',
      label: 'Ghost Drift',
      startProgress: 0,
      endProgress: 0.22,
      phase: 'intro',
      summary: 'Quiet opening with deceptive calm and isolated targets.',
      enemyFocus: [
        { type: 'scout', weight: 34 },
        { type: 'fighter', weight: 66 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.78,
      musicIntensity: 0.36,
    },
    {
      id: 'ghostlight-ambushes',
      label: 'Fog Ambushes',
      startProgress: 0.22,
      endProgress: 0.66,
      phase: 'hazard',
      summary: 'Enemies enter in offset timing from both sides as visibility pulses intensify.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 22 },
        { type: 'swarm', weight: 30 },
        { type: 'gunship', weight: 14 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 1.98,
      hazardEvents: [
        { type: 'nebula-ambush', cadenceMs: 2200, intensity: 0.72 },
        { type: 'minefield', cadenceMs: 3200, intensity: 0.38 },
      ],
      musicIntensity: 0.82,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Luminous Ghostwake',
      mood: 'ethereal wonder with a quiet ache',
      tempoFeel: 'floating and whisper-close',
      musicalStyle: 'luminous drift tones over a hidden heartbeat and feathered shimmer hiss',
      intensity: 'medium with ghostly swells',
      shiftMoments: ['Fog ambushes bring the hidden heartbeat forward.', 'Boss cue keeps the dreamlike bed but adds a more deliberate chase layer.'],
      bossCueName: 'Luminous Ghostwake: Veil Manta',
    },
    {
      tempo: 102,
      rootHz: 92.5,
      stepsPerBeat: 4,
      masterGain: 0.92,
      expression: {
        ...trackExpressionPresets.orbit,
        accent: { amount: 0.07, patternBias: 0.12, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sine',
        pattern: [0, null, null, null, 3, null, null, null, 8, null, null, null, 10, null, 8, null],
        gain: 0.15,
        durationSteps: 4,
        expression: {
          ...layerExpressionPresets.pad,
          ...layerExpressionPresets.drift,
          accent: { ...layerExpressionPresets.gentleAccent.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: [null, null, 15, null, null, null, 12, null, null, null, 17, null, null, null, 15, null],
        gain: 0.032,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1400,
        expression: {
          ...layerExpressionPresets.pluck,
          ...layerExpressionPresets.orbit,
          accent: { amount: 0.08, patternBias: 0.14, emphasisSteps: [2, 6, 10, 14] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: [19, null, null, null, 17, null, null, null, 22, null, null, null, 24, null, null, null],
        gain: 0.034,
        durationSteps: 4,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.swell,
          ...layerExpressionPresets.orbit,
          ...layerExpressionPresets.vibrato,
        },
      },
      noise: {
        pattern: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        gain: 0.012,
        filterHz: 1500,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.shimmer,
        },
      },
    },
    {
      tempo: 108,
      masterGain: 0.98,
      expression: {
        ...trackExpressionPresets.orbit,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 210, rateHz: 0.88 },
        accent: { amount: 0.13, patternBias: 0.24, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { gain: 0.16 },
      pulse: {
        waveform: 'square',
        pattern: [null, 15, null, 12, null, 15, null, 17, null, 19, null, 17, null, 15, null, 12],
        gain: 0.042,
      },
      lead: { waveform: 'triangle', gain: 0.039 },
      noise: {
        gain: 0.016,
        filterHz: 2000,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.1, patternBias: 0.14, emphasisSteps: [6, 13] },
        },
      },
    }
  ),
};
