import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const GHOSTLIGHT_VEIL_LEVEL: LevelConfig = {
  name: 'Mirage Archive',
  planetName: 'Nacre Vault',
  destination: 'Mnemonic nebula stacks at the Nacre Archive ring',
  visualTheme: 'Pale cyan ghosts, lilac fog bands, and intermittent memory flashes.',
  coreGameplayIdea: 'Information pressure stage where fake calm and sudden ambushes battle player composure.',
  pacingSummary: 'Quiet drift, ambush pulses, false-safe corridors, and pursuit boss entry.',
  enemyCompositionSummary: 'Swarms and fighters spike perception load while bombers punish hesitation.',
  hazardSummary: 'Nebula ambushes, gravity pulls, and deceptive mine pockets.',
  bossConcept: 'Archivist Shade hunts with pursuit loops and sudden angle collapses.',
  difficultyRole: 'Uncertainty stress test emphasizing anticipation over reaction alone.',
  journeyNote: 'The archive seems serene until every quiet pocket reveals a trap.',
  bgColor: '#070819',
  accentColor: 0x9be5ff,
  nebulaColor: 0x4d3b79,
  nebulaAlpha: 0.18,
  colorGrade: { brightness: 0.03, contrast: 1.15, saturation: 0.96 },
  planetPalette: [0x768dcb, 0xc3e8ff],
  enemies: [
    { type: 'fighter', weight: 28 },
    { type: 'bomber', weight: 18 },
    { type: 'swarm', weight: 31 },
    { type: 'gunship', weight: 23 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 1.92,
  levelDistance: 18800,
  hasBoss: true,
  boss: {
    name: 'Archivist Shade',
    maxHp: 3600,
    phase1Cooldown: 840,
    phase2Cooldown: 410,
    phase2MoveSpeed: 226,
    attackStyle: 'pursuit',
    phase1SpreadShotCount: 7,
    phase1SpreadArcDegrees: 68,
    phase1BulletSpeedScale: 1.02,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 112,
    phase2BulletSpeedScale: 1.09,
  },
  bossTriggerProgress: 0.64,
  asteroidInterval: 3250,
  sections: [
    {
      id: 'archive-whisper',
      label: 'Whisper Shell',
      startProgress: 0,
      endProgress: 0.14,
      phase: 'intro',
      summary: 'Soft opening with rare contacts to set deceptive calm.',
      musicIntensity: 0.42,
    },
    {
      id: 'archive-blinkwalls',
      label: 'Blinkwalls',
      startProgress: 0.14,
      endProgress: 0.32,
      phase: 'build',
      summary: 'Ambush bursts occur at readable cadence but variable lane origin.',
      hazardEvents: [{ type: 'nebula-ambush', cadenceMs: 1850, intensity: 0.68 }],
      musicIntensity: 0.62,
    },
    {
      id: 'archive-drag',
      label: 'Memory Drag',
      startProgress: 0.32,
      endProgress: 0.5,
      phase: 'hazard',
      summary: 'Gravity wells stretch dodges while swarms force commitment errors.',
      hazardEvents: [{ type: 'gravity-well', cadenceMs: 2100, intensity: 0.62 }],
      musicIntensity: 0.79,
    },
    {
      id: 'archive-false-safety',
      label: 'False Safety',
      startProgress: 0.5,
      endProgress: 0.62,
      phase: 'climax',
      summary: 'Mine pockets break apparent safe lanes during high enemy pressure.',
      spawnRateMultiplier: 2.0,
      hazardEvents: [
        { type: 'minefield', cadenceMs: 1700, intensity: 0.74 },
        { type: 'nebula-ambush', cadenceMs: 1900, intensity: 0.7 },
      ],
      musicIntensity: 0.94,
    },
    {
      id: 'archive-hunter-call',
      label: 'Hunter Call',
      startProgress: 0.62,
      endProgress: 0.64,
      phase: 'boss-approach',
      summary: 'A short tonal dip telegraphs pursuit boss onset.',
      musicIntensity: 1,
    },
  ],
  music: createSignatureMusic({
    cueName: 'Archive Ghostline',
    bossCueName: 'Archive Ghostline: Shade Pursuit',
    mood: 'eerie suspense with sharp panic spikes',
    tempoFeel: 'floating pulse that snaps into chase',
    style: 'ambient motifs over tightening rhythmic teeth',
    intensity: 'high',
    shifts: ['False safety section compresses phrase spacing and raises tremolo emphasis.'],
    tempo: 108,
    rootHz: 103.83,
    patternRoot: 0,
    bassPattern: bassPatterns.syncopatedOstinato,
    pulsePattern: arpeggiatorPatterns.reverbBloom,
    leadPattern: arpeggiatorPatterns.phrygianMystery,
    bossBassPattern: bassPatterns.mawChase,
    bossPulsePattern: arpeggiatorPatterns.stalkingPursuit,
    bossLeadPattern: arpeggiatorPatterns.darkChromatic,
    bossTempo: 120,
    intent: {
      deterministicSeed: 'ghostlight-veil-archive-ghostline',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'phrygian',
        chordProgressionTags: ['suspended-dread', 'echo-minor-cells'],
        rhythmicFeel: 'floating pulse with snap accents',
        energyProfile: { baseline: 0.45, peak: 0.92, curve: 'build-release' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'locrian',
        chordProgressionTags: ['chromatic-hunter-line', 'diminished-pressure'],
        rhythmicFeel: 'predator chase subdivisions',
        energyProfile: { baseline: 0.7, peak: 0.97, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'diminished' },
            { degree: 2, barsDuration: 1, quality: 'minor' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'diminished' },
          ],
        },
      },
    },
  }),
};
