import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets, arpeggiatorPatterns, bassPatterns } from '../musicHelpers';

export const GHOSTLIGHT_VEIL_LEVEL: LevelConfig = {
  name: 'Ghostlight Veil',
  planetName: 'Nacre Reach',
  destination: 'A luminous nebula wall around Nacre Reach',
  visualTheme: 'Pale blue-violet fog, ghostly glows, and low-visibility pockets.',
  coreGameplayIdea: 'Ambush patterns emerge out of fog bands while visibility keeps changing.',
  pacingSummary: 'Slow drift, deceptive quiet, then repeated pincer ambushes.',
  enemyCompositionSummary: 'Swarms and fighters create shape-changing flanks while bombers punish tunnel vision.',
  hazardSummary: 'Nebula ambush zones and erratic mine-like pressure.',
  bossConcept: 'A cloaking manta that disappears into fog and returns with spread formations.',
  difficultyRole: 'Raises information pressure instead of just numbers.',
  journeyNote: 'The path narrows through a beautiful but hostile cloud sea where sensor ghosts lie.',
  bgColor: '#090b1e',
  accentColor: 0xb3a0ff,
  nebulaColor: 0x5a4ec1,
  nebulaAlpha: 0.16,
  colorGrade: { brightness: 0.05, contrast: 1.1, saturation: 1.16 },
  planetPalette: [0x6650aa, 0x9f89da],
  enemies: [
    { type: 'scout', weight: 12 },
    { type: 'fighter', weight: 28 },
    { type: 'bomber', weight: 16 },
    { type: 'swarm', weight: 24 },
    { type: 'gunship', weight: 20 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.04,
  levelDistance: 19000,
  hasBoss: true,
  boss: {
    name: 'Veil Manta',
    maxHp: 90,
    phase1Cooldown: 820,
    phase2Cooldown: 410,
    phase2MoveSpeed: 225,
    attackStyle: 'pursuit',
    phase1SpreadShotCount: 7,
    phase1SpreadArcDegrees: 66,
    phase1BulletSpeedScale: 1.03,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 110,
    phase2BulletSpeedScale: 1.08,
  },
  bossTriggerProgress: 0.63,
  asteroidInterval: 4200,
  sections: [
    {
      id: 'ghostlight-drift',
      label: 'Ghost Drift',
      startProgress: 0,
      endProgress: 0.13,
      phase: 'intro',
      summary: 'Quiet opening with deceptive calm and isolated targets.',
      enemyFocus: [
        { type: 'scout', weight: 34 },
        { type: 'fighter', weight: 66 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.78,
      musicIntensity: 0.36,
    },
    {
      id: 'ghostlight-shimmer',
      label: 'Shimmer Lanes',
      startProgress: 0.13,
      endProgress: 0.30,
      phase: 'build',
      summary: 'Fog pockets thicken as enemies learn to use the cover to approach unseen.',
      enemyFocus: [
        { type: 'fighter', weight: 40 },
        { type: 'scout', weight: 25 },
        { type: 'swarm', weight: 25 },
        { type: 'bomber', weight: 10 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.88,
      asteroidInterval: 4000,
      musicIntensity: 0.52,
    },
    {
      id: 'ghostlight-ambushes',
      label: 'Fog Ambushes',
      startProgress: 0.30,
      endProgress: 0.48,
      phase: 'hazard',
      summary: 'Enemies enter in offset timing from both sides as visibility pulses intensify.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 22 },
        { type: 'swarm', weight: 30 },
        { type: 'gunship', weight: 14 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 1.98,
      hazardEvents: [
        { type: 'nebula-ambush', cadenceMs: 2200, intensity: 0.72 },
        { type: 'minefield', cadenceMs: 3200, intensity: 0.38 },
      ],
      musicIntensity: 0.82,
    },
    {
      id: 'ghostlight-pincer',
      label: 'Pincer Fog',
      startProgress: 0.48,
      endProgress: 0.59,
      phase: 'climax',
      summary: 'Maximum fog density. Swarms pour from both flanks while bombers cut escape lanes.',
      enemyFocus: [
        { type: 'swarm', weight: 35 },
        { type: 'fighter', weight: 30 },
        { type: 'bomber', weight: 20 },
        { type: 'gunship', weight: 15 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 2.1,
      asteroidInterval: 3800,
      hazardEvents: [
        { type: 'nebula-ambush', cadenceMs: 1800, intensity: 0.8 },
        { type: 'minefield', cadenceMs: 2800, intensity: 0.45 },
      ],
      musicIntensity: 0.9,
    },
    {
      id: 'ghostlight-reveal',
      label: 'Veil Thinning',
      startProgress: 0.59,
      endProgress: 0.63,
      phase: 'boss-approach',
      summary: 'The fog parts and the Veil Manta glides into view.',
      musicIntensity: 0.95,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Ethereal Mist',
      mood: 'ethereal wonder with quiet ache',
      tempoFeel: 'floating in luminous fog',
      musicalStyle: 'suspended harmonies drifting over sparse ostinato with echoing wide intervals',
      intensity: 'medium with ghostly atmosphere',
      shiftMoments: ['Fog ambushes bring quartal motion forward.', 'Boss cue adds call-response intensity while keeping misty texture.'],
      bossCueName: 'Ethereal Mist: Veil Manta',
    },
    {
      tempo: 86,
      rootHz: 185,
      stepsPerBeat: 4,
      masterGain: 0.78,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        stereo: { ...trackExpressionPresets.expansiveSpace.stereo, width: 0.48, rateHz: 0.05 },
        accent: { amount: 0.04, patternBias: 0.08, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sine',
        pattern: bassPatterns.rhythmicOstinato(0),
        gain: 0.12,
        durationSteps: 4,
        expression: {
          ...layerExpressionPresets.longPad,
          ...layerExpressionPresets.wideSpace,
          accent: { ...layerExpressionPresets.breathPulse.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.quartalDrift(8),
        gain: 0.024,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1250,
        expression: {
          ...layerExpressionPresets.softPluck,
          ...layerExpressionPresets.wideSpace,
          accent: { amount: 0.06, patternBias: 0.1, emphasisSteps: [2, 6, 10, 14] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.suspended2(19),
        gain: 0.022,
        durationSteps: 4,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.slowSwell,
          ...layerExpressionPresets.wideSpace,
          ...layerExpressionPresets.gentleVibrato,
        },
      },
      noise: {
        pattern: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        gain: 0.008,
        filterHz: 1350,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.dreamyDrift,
          stereo: { ...noiseExpressionPresets.dreamyDrift.stereo, width: 0.45, rateHz: 0.06 },
        },
      },
    },
    {
      tempo: 92,
      masterGain: 0.86,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 170, rateHz: 0.7 },
        accent: { amount: 0.09, patternBias: 0.18, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { 
        pattern: bassPatterns.sparseWalk(0),
        gain: 0.13 
      },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.echoPhrase(8),
        gain: 0.034,
      },
      lead: { 
        waveform: 'sine', 
        pattern: arpeggiatorPatterns.wideLeap(19),
        gain: 0.028 
      },
      noise: {
        gain: 0.011,
        filterHz: 1750,
        expression: {
          ...noiseExpressionPresets.dreamyDrift,
          accent: { amount: 0.07, patternBias: 0.1, emphasisSteps: [6, 13] },
        },
      },
    }
  ),
};
