import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const ION_STORM_SECTOR_LEVEL: LevelConfig = {
  name: 'Magnetar Foundry',
  planetName: 'Rigel Forge',
  destination: 'Electromagnetic shipyard shell around Rigel Forge',
  visualTheme: 'Emerald ion storms over industrial silhouettes and live power conduits.',
  coreGameplayIdea: 'Teaches sustained pressure management with clear pre-boss escalation language.',
  pacingSummary: 'Charge-up lanes, storm bursts, gravity distortions, then first guardian duel.',
  enemyCompositionSummary: 'Balanced lineup with swarms as spacing disruptors and bombers as tempo breakers.',
  hazardSummary: 'Energy storms plus gravity tug moments and timed debris punctuation.',
  bossConcept: 'Arc Warden Khepri channels storms into expanding denial arcs and fast resets.',
  difficultyRole: 'First full-system exam and first boss mastery check.',
  journeyNote: 'The frontier shifts from weather to warfare as the foundry locks onto intruders.',
  bgColor: '#07150f',
  accentColor: 0x52f7a6,
  nebulaColor: 0x145c3b,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.08, contrast: 1.12, saturation: 0.94 },
  planetPalette: [0x3d9f69, 0x77f5b4],
  enemies: [
    { type: 'scout', weight: 22 },
    { type: 'fighter', weight: 34 },
    { type: 'bomber', weight: 17 },
    { type: 'swarm', weight: 27 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.42,
  levelDistance: 14600,
  hasBoss: true,
  boss: {
    name: 'Arc Warden Khepri',
    maxHp: 1200,
    phase1Cooldown: 1140,
    phase2Cooldown: 590,
    phase2MoveSpeed: 170,
    attackStyle: 'barrage',
    phase1SpreadShotCount: 5,
    phase1SpreadArcDegrees: 62,
    phase1BulletSpeedScale: 0.86,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 66,
    phase2BulletSpeedScale: 0.94,
  },
  bossTriggerProgress: 0.72,
  asteroidInterval: 3900,
  sections: [
    {
      id: 'foundry-inlet',
      label: 'Charge Inlet',
      startProgress: 0,
      endProgress: 0.14,
      phase: 'intro',
      summary: 'Predictable openings establish storm telegraph expectations.',
      musicIntensity: 0.38,
      tensionArc: 'constant',
      vatTarget: { valence: 0.06, arousal: 0.4, tension: 0.34 },
    },
    {
      id: 'foundry-field',
      label: 'Live Conduits',
      startProgress: 0.14,
      endProgress: 0.34,
      phase: 'build',
      summary: 'Energy bursts and mixed squads increase decision frequency.',
      hazardEvents: [{ type: 'energy-storm', cadenceMs: 2300, intensity: 0.52 }],
      spawnRateMultiplier: 1.46,
      musicIntensity: 0.6,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.04, arousal: 0.58, tension: 0.52 },
    },
    {
      id: 'foundry-rift',
      label: 'Flux Rift',
      startProgress: 0.34,
      endProgress: 0.54,
      phase: 'hazard',
      summary: 'Gravity pulses arrive alongside debris to force deliberate lane commits.',
      encounterSizeOverride: { min: 2, max: 2 },
      hazardEvents: [
        { type: 'gravity-well', cadenceMs: 2600, intensity: 0.48 },
        { type: 'debris-surge', cadenceMs: 2700, intensity: 0.42 },
      ],
      musicIntensity: 0.74,
      tensionArc: 'waves',
      vatTarget: { valence: -0.12, arousal: 0.68, tension: 0.66 },
    },
    {
      id: 'foundry-overload',
      label: 'Overload Rail',
      startProgress: 0.54,
      endProgress: 0.7,
      phase: 'climax',
      summary: 'Fast storm cadence and denser bomber entries spike pre-boss tension.',
      spawnRateMultiplier: 1.58,
      asteroidInterval: 3200,
      hazardEvents: [{ type: 'energy-storm', cadenceMs: 1820, intensity: 0.68 }],
      musicIntensity: 0.88,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.2, arousal: 0.82, tension: 0.82 },
    },
    {
      id: 'foundry-gate',
      label: 'Guardian Rail',
      startProgress: 0.7,
      endProgress: 0.72,
      phase: 'boss-approach',
      summary: 'Systems quiet for a beat before the warden engages.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 5200,
      musicIntensity: 0.8,
      tensionArc: 'constant',
      vatTarget: { valence: -0.08, arousal: 0.44, tension: 0.5 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Forge Current',
    bossCueName: 'Forge Current: Khepri Coil',
    mood: 'disciplined urgency with electric bite',
    tempoFeel: 'marching charge with burst accents',
    style: 'driving electro pulse over metallic bass pressure',
    intensity: 'medium-high',
    shifts: ['Overload rail accelerates percussion density and low-end motion before boss drop.'],
    tempo: 101,
    rootHz: 98,
    patternRoot: 0,
    bassPattern: bassPatterns.drivingPulseBass,
    pulsePattern: arpeggiatorPatterns.drivingPulse,
    leadPattern: arpeggiatorPatterns.forwardMomentum,
    bossBassPattern: bassPatterns.aggressiveBass,
    bossPulsePattern: arpeggiatorPatterns.martialStomp,
    bossLeadPattern: arpeggiatorPatterns.aggressiveAttack,
    intent: {
      deterministicSeed: 'ion-storm-sector-forge-current',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'dorian',
        chordProgressionTags: ['electro-minor-loop', 'suspended-charge'],
        rhythmicFeel: 'march pulse with burst accents',
        energyProfile: { baseline: 0.44, peak: 0.82, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 4, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'aeolian',
        chordProgressionTags: ['minor-dominant-drive', 'descending-threat'],
        rhythmicFeel: 'stomped pursuit cadence',
        energyProfile: { baseline: 0.66, peak: 0.92, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 6, barsDuration: 1, quality: 'major' },
            { degree: 3, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
          ],
        },
      },
    },
  }),
};
