import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets } from '../musicHelpers';

export const ION_STORM_SECTOR_LEVEL: LevelConfig = {
  name: 'Ion Storm Sector',
  planetName: 'Rigel Station',
  destination: 'Charged storm route to Rigel Station',
  visualTheme: 'Green ion sheets and electromagnetic haze.',
  coreGameplayIdea: 'Swarm management inside a louder bullet environment.',
  pacingSummary: 'Storm front buildup, hectic mid-stage crossing, then boss sirens.',
  enemyCompositionSummary: 'Balanced roster with the first swarms.',
  hazardSummary: 'Frequent asteroid traffic and electrical storm surges.',
  bossConcept: 'A storm-core warship that turns the level’s crossfire into a formal exam.',
  difficultyRole: 'First real wall and first boss fight.',
  journeyNote: 'The player reaches defended industrial space where the frontier starts fighting back.',
  bgColor: '#001108',
  accentColor: 0x44ff88,
  nebulaColor: 0x116633,
  nebulaAlpha: 0.10,
  colorGrade: { brightness: 0.08, contrast: 1.12, saturation: 0.92 },
  planetPalette: [0x448844, 0x66aa66],
  enemies: [
    { type: 'scout', weight: 35 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 15 },
    { type: 'swarm', weight: 20 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.4,
  levelDistance: 9600,
  hasBoss: true,
  boss: {
    name: 'Storm Binder',
    maxHp: 48,
    phase1Cooldown: 1200,
    phase2Cooldown: 650,
    phase2MoveSpeed: 150,
    attackStyle: 'barrage',
    phase1SpreadShotCount: 5,
    phase1SpreadArcDegrees: 72,
    phase1BulletSpeedScale: 0.8,
    phase2SpiralShotCount: 2,
    phase2SpiralTurnRate: 56,
    phase2BulletSpeedScale: 0.9,
  },
  bossTriggerProgress: 0.72,
  asteroidInterval: 4000,
  sections: [
    {
      id: 'ion-front',
      label: 'Front Edge',
      startProgress: 0,
      endProgress: 0.28,
      phase: 'build',
      summary: 'Scouts and fighters ride the edge of the storm.',
      musicIntensity: 0.4,
    },
    {
      id: 'ion-swarm',
      label: 'Charged Swarm',
      startProgress: 0.28,
      endProgress: 0.62,
      phase: 'hazard',
      summary: 'Swarms and asteroids overlap to pressure lateral movement.',
      asteroidInterval: 3300,
      hazardEvents: [{ type: 'energy-storm', cadenceMs: 2600, intensity: 0.6 }],
      musicIntensity: 0.72,
    },
    {
      id: 'ion-boss-lane',
      label: 'Storm Eye',
      startProgress: 0.62,
      endProgress: 0.72,
      phase: 'boss-approach',
      summary: 'Enemy count thins out and warning energy builds.',
      musicIntensity: 0.8,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Static Pressure',
      mood: 'charged concentration',
      tempoFeel: 'measured electrical stride',
      musicalStyle: 'storm-lit synth bass with airy current hiss and a patient warning motif',
      intensity: 'medium with sharper peaks',
      shiftMoments: ['Storm crossings thicken the charged air texture.', 'Boss music escalates by adding counterpulse and grain around the motif.'],
      bossCueName: 'Static Pressure: Storm Binder',
    },
    {
      tempo: 114,
      rootHz: 116.54,
      stepsPerBeat: 4,
      masterGain: 0.96,
      expression: {
        ...trackExpressionPresets.subtleWidth,
        accent: { amount: 0.09, patternBias: 0.2, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'triangle',
        pattern: [0, null, null, null, 2, null, null, null, 7, null, null, null, 9, null, 7, null],
        gain: 0.15,
        durationSteps: 4,
        filterHz: 820,
        expression: {
          ...layerExpressionPresets.pad,
          ...layerExpressionPresets.drift,
          accent: { ...layerExpressionPresets.gentleAccent.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: [12, null, null, 12, null, 14, null, null, 17, null, null, 14, null, 12, null, null],
        gain: 0.042,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1700,
        expression: {
          ...layerExpressionPresets.pluck,
          accent: { amount: 0.14, patternBias: 0.22, emphasisSteps: [0, 3, 8, 11] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: [null, 14, null, 17, null, 14, null, 12, null, 19, null, 17, null, 14, null, 12],
        gain: 0.034,
        durationSteps: 3,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.swell,
          ...layerExpressionPresets.vibrato,
        },
      },
      noise: {
        pattern: [0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
        gain: 0.013,
        filterHz: 1600,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.08, patternBias: 0.12, emphasisSteps: [2, 5, 9, 13] },
        },
      },
    },
    {
      tempo: 120,
      masterGain: 1.02,
      expression: {
        ...trackExpressionPresets.subtleWidth,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 260, rateHz: 1.1 },
        accent: { amount: 0.16, patternBias: 0.38, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { gain: 0.17, filterHz: 950 },
      pulse: {
        waveform: 'square',
        pattern: [12, null, 12, null, 14, null, 12, null, 17, null, 14, null, 12, null, 10, null],
        gain: 0.052,
      },
      lead: { waveform: 'triangle', gain: 0.042 },
      noise: {
        gain: 0.018,
        filterHz: 2100,
        expression: {
          ...noiseExpressionPresets.grit,
          accent: { amount: 0.12, patternBias: 0.22, emphasisSteps: [1, 5, 9, 13] },
        },
      },
    }
  ),
};
