import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../music';
import { createSignatureMusic } from './reimaginedMusic';

export const ION_STORM_SECTOR_LEVEL: LevelConfig = {
  name: 'Ember Monsoon',
  planetName: 'Cinderreach',
  destination: 'Ember storm front sweeping Cinderreach',
  visualTheme: 'Rust-amber ember rain over dark basalt silhouettes and heat haze.',
  coreGameplayIdea: 'Sowers lay drifting minefields while ember storms force lane commits.',
  pacingSummary: 'Mine-denial lessons build into a mid-boss elite wave and the first boss duel.',
  enemyCompositionSummary: 'Fighters and divers pressure lanes, sowers debut area denial, and swarms disrupt spacing.',
  hazardSummary: 'Energy storms return as weather; minefields drift from sowers.',
  bossConcept: 'Pyre Herald channels the monsoon into barrage arcs; the first boss, taught at 60% by an elite wave.',
  difficultyRole: 'Gentle-to-ramp pivot and first boss mastery check.',
  journeyNote: 'The frontier shifts from weather to warfare as ember rain heralds the Pyre Herald.',
  bgColor: '#140806',
  accentColor: 0xff9a4d,
  nebulaColor: 0x5c2412,
  nebulaAlpha: 0.13,
  colorGrade: { brightness: 0.08, contrast: 1.1, saturation: 1.0 },
  planetPalette: [0xa8481f, 0xffc27a],
  enemies: [
    { type: 'fighter', weight: 30 },
    { type: 'sower', weight: 12 },
    { type: 'swarm', weight: 27 },
    { type: 'diver', weight: 25 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.35,
  levelDistance: 14500,
  hasBoss: true,
  boss: {
    name: 'Pyre Herald',
    maxHp: 1500,
    phase1Cooldown: 1050,
    phase2Cooldown: 560,
    phase2MoveSpeed: 170,
    phaseTransitionPauseMs: 260,
    attackStyle: 'barrage',
    phase1SpreadShotCount: 5,
    phase1SpreadArcDegrees: 70,
    phase1BulletSpeedScale: 0.92,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 80,
    phase2BulletSpeedScale: 0.98,
  },
  bossTriggerProgress: 0.72,
  asteroidInterval: 3900,
  sections: [
    {
      id: 'foundry-inlet',
      label: 'Charge Inlet',
      startProgress: 0,
      endProgress: 0.14,
      phase: 'intro',
      summary: 'Ember rain opens gently while fighters probe the lanes ahead of the gathering storms.',
      musicIntensity: 0.38,
      visualModifiers: {
        atmosphereAlpha: 0.95,
        driftScale: 0.96,
        twinkleScale: 0.88,
        landmarkAlpha: 0.92,
      },
      tensionArc: 'constant',
      vatTarget: { valence: 0.06, arousal: 0.4, tension: 0.34 },
    },
    {
      id: 'foundry-field',
      label: 'Sower Drift',
      startProgress: 0.14,
      endProgress: 0.34,
      phase: 'build',
      summary: 'Sowers drift onto the field behind fighter screens, seeding the denial lessons to come.',
      enemyFocus: [
        { type: 'fighter', weight: 40 },
        { type: 'sower', weight: 35 },
        { type: 'diver', weight: 25 },
      ],
      waves: [
        {
          id: 'l3-diver-vee-ember',
          atMs: 3200,
          formation: 'vee',
          type: 'diver',
          count: 3,
          lane: 3,
          telegraph: 'warning',
          notes: 'Warned diver vee keeps the sower debut readable.',
        },
      ],
      spawnRateMultiplier: 1.46,
      musicIntensity: 0.6,
      visualModifiers: {
        atmosphereAlpha: 1.02,
        driftScale: 1.06,
        twinkleScale: 0.98,
        landmarkAlpha: 1.0,
        hazardResponseScale: 1.14,
      },
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.04, arousal: 0.58, tension: 0.52 },
    },
    {
      id: 'foundry-rift',
      label: 'Minefield Rift',
      startProgress: 0.34,
      endProgress: 0.54,
      phase: 'hazard',
      summary: 'Sowers lay drifting minefields across the lanes, forcing deliberate commits between debris bursts.',
      encounterSizeOverride: { min: 2, max: 2 },
      enemyFocus: [
        { type: 'sower', weight: 40 },
        { type: 'swarm', weight: 30 },
        { type: 'fighter', weight: 30 },
      ],
      hazardEvents: [
        {
          type: 'minefield',
          cadenceMs: 2400,
          intensity: 0.5,
          notes: 'Sower-laid fields: drifting destructible mines on a readable cadence.',
        },
        { type: 'debris-surge', cadenceMs: 3000, intensity: 0.4 },
      ],
      waves: [
        {
          id: 'l3-swarm-ring-rift',
          atMs: 5200,
          formation: 'ring',
          type: 'swarm',
          count: 5,
          lane: 3,
          telegraph: 'none',
          notes: 'Swarm ring blooms between mine layers to keep the chain fed.',
        },
      ],
      musicIntensity: 0.74,
      visualModifiers: {
        atmosphereAlpha: 1.06,
        driftScale: 1.08,
        twinkleScale: 1.02,
        landmarkAlpha: 1.06,
        hazardResponseScale: 1.18,
      },
      tensionArc: 'waves',
      vatTarget: { valence: -0.12, arousal: 0.68, tension: 0.66 },
    },
    {
      id: 'foundry-overload',
      label: 'Overload Rail',
      startProgress: 0.54,
      endProgress: 0.7,
      phase: 'climax',
      summary: 'The energy storm returns as the weather while a gunship elite wave teaches the Herald duel.',
      spawnRateMultiplier: 1.58,
      asteroidInterval: 3200,
      hazardEvents: [{ type: 'energy-storm', cadenceMs: 2100, intensity: 0.6 }],
      waves: [
        {
          id: 'l3-gunship-midboss',
          atMs: 6000,
          formation: 'column',
          type: 'gunship',
          count: 2,
          lane: 3,
          telegraph: 'warning',
          midBossBeat: true,
          notes: 'Mid-boss elite wave: a warned gunship column rehearses boss discipline at the heat front.',
        },
      ],
      recoveryDrops: [
        {
          id: 'l3-health-heat-front',
          triggerProgress: 0.55,
          type: 'health',
          lane: 'center',
          notes: 'Relief beat: a breather to stabilize after the storm front peaks.',
        },
      ],
      musicIntensity: 0.88,
      visualModifiers: {
        atmosphereAlpha: 1.12,
        driftScale: 1.1,
        twinkleScale: 1.06,
        landmarkAlpha: 1.12,
        hazardResponseScale: 1.24,
      },
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.2, arousal: 0.82, tension: 0.82 },
    },
    {
      id: 'foundry-gate',
      label: 'Guardian Rail',
      startProgress: 0.7,
      endProgress: 0.72,
      phase: 'boss-approach',
      summary: 'The monsoon hushes for a breath before the Pyre Herald channels the storms.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 5200,
      recoveryDrops: [
        {
          id: 'l3-shield-preboss',
          triggerProgress: 0.5,
          type: 'shield',
          lane: 'center',
          notes: 'Relief beat: a pre-boss breather shield so pilots stabilize at the gate.',
        },
      ],
      musicIntensity: 0.8,
      visualModifiers: {
        atmosphereAlpha: 0.92,
        driftScale: 0.9,
        twinkleScale: 0.72,
        landmarkAlpha: 1.08,
      },
      tensionArc: 'constant',
      vatTarget: { valence: -0.08, arousal: 0.44, tension: 0.5 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Ember Front',
    bossCueName: 'Ember Front: Pyre Herald',
    mood: 'smoldering urgency with sparks of defiance',
    tempoFeel: 'driving ember march',
    style: 'smoldering electro pulse over metallic bass pressure',
    intensity: 'medium-high',
    shifts: ['Overload rail accelerates percussion density and low-end motion before boss drop.'],
    tempo: 108,
    rootHz: 98,
    patternRoot: 0,
    bassPattern: bassPatterns.drivingPulseBass,
    pulsePattern: arpeggiatorPatterns.drivingPulse,
    leadPattern: arpeggiatorPatterns.forwardMomentum,
    bossBassPattern: bassPatterns.aggressiveBass,
    bossPulsePattern: arpeggiatorPatterns.martialStomp,
    bossLeadPattern: arpeggiatorPatterns.aggressiveAttack,
    intent: {
      deterministicSeed: 'ember-monsoon-pyre-front',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'dorian',
        chordProgressionTags: ['electro-minor-loop', 'suspended-charge'],
        rhythmicFeel: 'march pulse with burst accents',
        energyProfile: { baseline: 0.44, peak: 0.82, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 4, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'aeolian',
        chordProgressionTags: ['minor-dominant-drive', 'descending-threat'],
        rhythmicFeel: 'stomped pursuit cadence',
        energyProfile: { baseline: 0.66, peak: 0.92, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 6, barsDuration: 1, quality: 'major' },
            { degree: 3, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
          ],
        },
      },
    },
  }),
};
