import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets } from '../musicHelpers';

export const NEBULA_PASS_LEVEL: LevelConfig = {
  name: 'Nebula Pass',
  planetName: 'Vega Prime',
  destination: 'Veiled transit toward Vega Prime',
  visualTheme: 'Purple haze, dense cloud pockets, and flickering star visibility.',
  coreGameplayIdea: 'Visibility pressure and ambush timing rather than raw volume.',
  pacingSummary: 'Quiet drift, sudden interrupts, then a more crowded exit lane.',
  enemyCompositionSummary: 'Scouts, fighters, and the first bombers.',
  hazardSummary: 'Nebula pockets and obscured approach vectors.',
  bossConcept: 'No boss; the level sells unpredictability and rhythm shifts.',
  difficultyRole: 'Introduces ambush rhythm and mixed enemy composition.',
  journeyNote: 'The route leaves the safe belt and enters a hiding place for raiders.',
  bgColor: '#100022',
  accentColor: 0x8844ff,
  nebulaColor: 0x4422aa,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.06, contrast: 1.08, saturation: 1.18 },
  planetPalette: [0x884488, 0xaa66aa],
  enemies: [
    { type: 'scout', weight: 50 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 20 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.2,
  levelDistance: 8400,
  hasBoss: false,
  boss: null,
  bossTriggerProgress: 0.8,
  asteroidInterval: 4500,
  sections: [
    {
      id: 'nebula-drift',
      label: 'Drift Veil',
      startProgress: 0,
      endProgress: 0.3,
      phase: 'intro',
      summary: 'Longer sight lines collapse into slow visibility pulses.',
      musicIntensity: 0.25,
    },
    {
      id: 'nebula-ambush',
      label: 'Ghost Ambush',
      startProgress: 0.3,
      endProgress: 0.72,
      phase: 'hazard',
      summary: 'Bombers arrive behind obscuring haze while fighters pressure the midline.',
      hazardEvents: [{ type: 'nebula-ambush', cadenceMs: 2500, intensity: 0.55 }],
      musicIntensity: 0.6,
    },
    {
      id: 'nebula-breakout',
      label: 'Breakout Lane',
      startProgress: 0.72,
      endProgress: 1,
      phase: 'climax',
      summary: 'The player bursts through the cloud bank into a faster exit.',
      spawnRateMultiplier: 1.32,
      musicIntensity: 0.7,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Purple Drift',
      mood: 'mysterious and cocooned',
      tempoFeel: 'gliding with soft interruptions',
      musicalStyle: 'misty synth lullaby with floating pings and a silky pink-noise veil',
      intensity: 'low to medium',
      shiftMoments: ['Ambush pockets add extra plucks and gentle filter motion without breaking the haze.'],
      bossCueName: 'Purple Drift Break',
    },
    {
      tempo: 92,
      rootHz: 92.5,
      stepsPerBeat: 4,
      masterGain: 0.88,
      expression: {
        ...trackExpressionPresets.orbit,
        stereo: { ...trackExpressionPresets.orbit.stereo, width: 0.28, rateHz: 0.07 },
        accent: { amount: 0.06, patternBias: 0.12, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sine',
        pattern: [0, null, null, null, 3, null, null, null, 10, null, null, null, 5, null, 3, null],
        gain: 0.14,
        durationSteps: 4,
        expression: {
          ...layerExpressionPresets.pad,
          ...layerExpressionPresets.drift,
          accent: { ...layerExpressionPresets.gentleAccent.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: [null, 15, null, null, null, 10, null, null, null, 17, null, null, null, 15, null, null],
        gain: 0.032,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1300,
        expression: {
          ...layerExpressionPresets.pluck,
          ...layerExpressionPresets.orbit,
          accent: { amount: 0.08, patternBias: 0.14, emphasisSteps: [1, 9] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: [12, null, null, 15, null, null, 10, null, 17, null, null, 15, null, null, 12, null],
        gain: 0.03,
        durationSteps: 4,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.swell,
          ...layerExpressionPresets.orbit,
          ...layerExpressionPresets.vibrato,
        },
      },
      noise: {
        pattern: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        gain: 0.011,
        filterHz: 1350,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.shimmer,
          stereo: { ...noiseExpressionPresets.shimmer.stereo, width: 0.3, rateHz: 0.08 },
        },
      },
    },
    {
      tempo: 98,
      masterGain: 0.94,
      expression: {
        ...trackExpressionPresets.orbit,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 220, rateHz: 0.75 },
        accent: { amount: 0.1, patternBias: 0.22, emphasisSteps: [0, 4, 8, 12] },
      },
      pulse: {
        waveform: 'square',
        pattern: [null, 15, null, 12, null, 10, null, 12, null, 17, null, 15, null, 12, null, 10],
        gain: 0.04,
      },
      lead: { waveform: 'triangle', gain: 0.036 },
      noise: {
        gain: 0.015,
        filterHz: 1700,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.08, patternBias: 0.12, emphasisSteps: [5, 11] },
        },
      },
    }
  ),
};
