import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets, arpeggiatorPatterns, bassPatterns } from '../musicHelpers';

export const NEBULA_PASS_LEVEL: LevelConfig = {
  name: 'Nebula Pass',
  planetName: 'Vega Prime',
  destination: 'Veiled transit toward Vega Prime',
  visualTheme: 'Purple haze, dense cloud pockets, and flickering star visibility.',
  coreGameplayIdea: 'Visibility pressure and ambush timing rather than raw volume.',
  pacingSummary: 'Quiet drift, sudden interrupts, then a more crowded exit lane.',
  enemyCompositionSummary: 'Scouts, fighters, and the first bombers.',
  hazardSummary: 'Nebula pockets and obscured approach vectors.',
  bossConcept: 'No boss; the level sells unpredictability and rhythm shifts.',
  difficultyRole: 'Introduces ambush rhythm and mixed enemy composition.',
  journeyNote: 'The route leaves the safe belt and enters a hiding place for raiders.',
  bgColor: '#100022',
  accentColor: 0x8844ff,
  nebulaColor: 0x4422aa,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.06, contrast: 1.08, saturation: 1.18 },
  planetPalette: [0x884488, 0xaa66aa],
  enemies: [
    { type: 'scout', weight: 50 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 20 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.2,
  levelDistance: 12500,
  hasBoss: false,
  boss: null,
  bossTriggerProgress: 0.8,
  asteroidInterval: 4500,
  sections: [
    {
      id: 'nebula-entry',
      label: 'Nebula Entry',
      startProgress: 0,
      endProgress: 0.15,
      phase: 'intro',
      summary: 'A misty curtain of ionized gas opens the level with slow scouts.',
      enemyFocus: [
        { type: 'scout', weight: 72 },
        { type: 'fighter', weight: 28 },
      ],
      encounterSizeOverride: { min: 1, max: 2 },
      spawnRateMultiplier: 1.0,
      musicIntensity: 0.35,
    },
    {
      id: 'nebula-shroud',
      label: 'The Shroud',
      startProgress: 0.15,
      endProgress: 0.34,
      phase: 'build',
      summary: 'Visibility drops as the nebula thickens; enemies approach from unexpected angles.',
      enemyFocus: [
        { type: 'scout', weight: 45 },
        { type: 'fighter', weight: 40 },
        { type: 'swarm', weight: 15 },
      ],
      spawnRateMultiplier: 1.2,
      musicIntensity: 0.5,
    },
    {
      id: 'nebula-ambush-fog',
      label: 'Ambush Fog',
      startProgress: 0.34,
      endProgress: 0.54,
      phase: 'hazard',
      summary: 'Nebula ambushes trigger in dense fog pockets while mine-like hazards drift in.',
      enemyFocus: [
        { type: 'scout', weight: 35 },
        { type: 'fighter', weight: 35 },
        { type: 'swarm', weight: 30 },
      ],
      spawnRateMultiplier: 1.35,
      hazardEvents: [{ type: 'nebula-ambush', cadenceMs: 2400, intensity: 0.45 }],
      asteroidInterval: 5500,
      musicIntensity: 0.62,
    },
    {
      id: 'nebula-depths',
      label: 'Deep Nebula',
      startProgress: 0.54,
      endProgress: 0.78,
      phase: 'climax',
      summary: 'The densest part of the cloud. Fighters and swarms pour from all sides.',
      enemyFocus: [
        { type: 'fighter', weight: 45 },
        { type: 'swarm', weight: 30 },
        { type: 'bomber', weight: 15 },
        { type: 'scout', weight: 10 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.5,
      hazardEvents: [
        { type: 'nebula-ambush', cadenceMs: 2000, intensity: 0.6 },
        { type: 'ambient-asteroids', cadenceMs: 3000, intensity: 0.3 },
      ],
      musicIntensity: 0.75,
    },
    {
      id: 'nebula-exit',
      label: 'Cloud Break',
      startProgress: 0.78,
      endProgress: 1,
      phase: 'intro',
      summary: 'The nebula thins and visibility returns. A brief reward before the next sector.',
      spawnRateMultiplier: 0.8,
      asteroidInterval: 6000,
      musicIntensity: 0.35,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Purple Drift',
      mood: 'mysterious floating suspension',
      tempoFeel: 'weightless nebula drift with gentle undulation',
      musicalStyle: 'ethereal sus2 arpeggios over pedal-tone drone and silky suspended-noise haze',
      intensity: 'low to medium with suspended tension',
      shiftMoments: ['Ambush pockets introduce dorian modal colors and echo phrases without disturbing the veil.'],
      bossCueName: 'Purple Drift Break',
    },
    {
      tempo: 84,
      rootHz: 98.0, // G2+ - slightly sharp for mysterious tension
      stepsPerBeat: 4,
      masterGain: 0.8,
      expression: {
        ...trackExpressionPresets.gentleFlow,
        stereo: { ...trackExpressionPresets.gentleFlow.stereo, width: 0.42, rateHz: 0.05, phaseOffset: 0.3 },
        accent: { amount: 0.06, patternBias: 0.12, emphasisSteps: [0, 6, 10] },
      },
      bass: {
        waveform: 'sine',
        pattern: bassPatterns.pedalFifths(0),
        gain: 0.15,
        durationSteps: 4,
        expression: {
          ...layerExpressionPresets.longPad,
          ...layerExpressionPresets.etherialGlow,
          accent: { ...layerExpressionPresets.breathPulse.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.suspended2(10),
        gain: 0.026,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1400,
        expression: {
          ...layerExpressionPresets.softPluck,
          ...layerExpressionPresets.ambientDrift,
          accent: { amount: 0.08, patternBias: 0.14, emphasisSteps: [1, 5, 9, 13] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.reverbBloom(15),
        gain: 0.024,
        durationSteps: 4,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.slowSwell,
          ...layerExpressionPresets.etherialGlow,
          ...layerExpressionPresets.gentleVibrato,
        },
      },
      noise: {
        pattern: [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
        gain: 0.01,
        filterHz: 1300,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.dreamyDrift,
          stereo: { ...noiseExpressionPresets.dreamyDrift.stereo, width: 0.4, rateHz: 0.05 },
        },
      },
    },
    {
      tempo: 88,
      masterGain: 0.88,
      expression: {
        ...trackExpressionPresets.gentleFlow,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 200, rateHz: 0.55 },
        accent: { amount: 0.11, patternBias: 0.2, emphasisSteps: [0, 4, 8, 12] },
      },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.dorianFlair(10),
        gain: 0.038,
      },
      lead: { 
        waveform: 'sine', 
        pattern: arpeggiatorPatterns.echoPhrase(15),
        gain: 0.032 
      },
      noise: {
        gain: 0.013,
        filterHz: 1600,
        expression: {
          ...noiseExpressionPresets.dreamyDrift,
          accent: { amount: 0.09, patternBias: 0.12, emphasisSteps: [4, 10] },
        },
      },
    }
  ),
};
