import type { LevelConfig } from '../types';
import { createMusicProfile } from '../musicHelpers';

export const NEBULA_PASS_LEVEL: LevelConfig = {
  name: 'Nebula Pass',
  planetName: 'Vega Prime',
  destination: 'Veiled transit toward Vega Prime',
  visualTheme: 'Purple haze, dense cloud pockets, and flickering star visibility.',
  coreGameplayIdea: 'Visibility pressure and ambush timing rather than raw volume.',
  pacingSummary: 'Quiet drift, sudden interrupts, then a more crowded exit lane.',
  enemyCompositionSummary: 'Scouts, fighters, and the first bombers.',
  hazardSummary: 'Nebula pockets and obscured approach vectors.',
  bossConcept: 'No boss; the level sells unpredictability and rhythm shifts.',
  difficultyRole: 'Introduces ambush rhythm and mixed enemy composition.',
  journeyNote: 'The route leaves the safe belt and enters a hiding place for raiders.',
  bgColor: '#100022',
  accentColor: 0x8844ff,
  nebulaColor: 0x4422aa,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.06, contrast: 1.08, saturation: 1.18 },
  planetPalette: [0x884488, 0xaa66aa],
  enemies: [
    { type: 'scout', weight: 50 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 20 },
  ],
  encounterSize: { min: 1, max: 2 },
  spawnRateMultiplier: 1.2,
  levelDistance: 8400,
  hasBoss: false,
  boss: null,
  bossTriggerProgress: 0.8,
  asteroidInterval: 4500,
  sections: [
    {
      id: 'nebula-drift',
      label: 'Drift Veil',
      startProgress: 0,
      endProgress: 0.3,
      phase: 'intro',
      summary: 'Longer sight lines collapse into slow visibility pulses.',
      musicIntensity: 0.25,
    },
    {
      id: 'nebula-ambush',
      label: 'Ghost Ambush',
      startProgress: 0.3,
      endProgress: 0.72,
      phase: 'hazard',
      summary: 'Bombers arrive behind obscuring haze while fighters pressure the midline.',
      hazardEvents: [{ type: 'nebula-ambush', cadenceMs: 2500, intensity: 0.55 }],
      musicIntensity: 0.6,
    },
    {
      id: 'nebula-breakout',
      label: 'Breakout Lane',
      startProgress: 0.72,
      endProgress: 1,
      phase: 'climax',
      summary: 'The player bursts through the cloud bank into a faster exit.',
      spawnRateMultiplier: 1.32,
      musicIntensity: 0.7,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Purple Drift',
      mood: 'mysterious and slightly tense',
      tempoFeel: 'gliding but nervous',
      musicalStyle: 'ambient pads implied through soft oscillators and syncopated synth pings',
      intensity: 'medium',
      shiftMoments: ['Bring in higher pulse accents during ambush pockets.'],
      bossCueName: 'Purple Drift Break',
    },
    {
      tempo: 96,
      rootHz: 98,
      stepsPerBeat: 4,
      masterGain: 0.92,
      bass: {
        waveform: 'sine',
        pattern: [0, null, null, null, 3, null, null, null, 10, null, null, null, 5, null, null, null],
        gain: 0.16,
        durationSteps: 4,
      },
      pulse: {
        waveform: 'triangle',
        pattern: [null, 15, null, null, null, 10, null, null, null, 15, null, null, null, 17, null, null],
        gain: 0.04,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1500,
      },
      lead: {
        waveform: 'sine',
        pattern: [12, null, null, 15, null, null, 10, null, 12, null, null, 17, null, null, 15, null],
        gain: 0.038,
        durationSteps: 3,
        octaveShift: 1,
      },
      noise: {
        pattern: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        gain: 0.013,
        filterHz: 1400,
        durationSteps: 1,
      },
    },
    {
      tempo: 110,
      masterGain: 1.0,
      pulse: { waveform: 'square', gain: 0.05 },
      lead: { gain: 0.048 },
      noise: { gain: 0.016, filterHz: 1800 },
    }
  ),
};
