import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const OBSIDIAN_MAW_LEVEL: LevelConfig = {
  name: 'Glass Rift Narrows',
  planetName: 'Kharon Scar',
  destination: 'Fractured canyon trench at Kharon Scar',
  visualTheme: 'Black glass walls with ember seams and claustrophobic red edge-light.',
  coreGameplayIdea: 'A lockjaw canyon chapter where corridor authority dominates and micro-corrections decide survival.',
  pacingSummary: 'Open pressure, descent squeeze, lockjaw gauntlet, then predator encounter.',
  enemyCompositionSummary: 'Fighters and swarms force tight corrections while gunships punish over-corrections.',
  hazardSummary: 'Corridor-first hazard language with debris punish windows and trap pulls inside narrowing lanes.',
  bossConcept: 'Rift Basilisk relentlessly chases and seals escape vectors.',
  difficultyRole: 'Signature mechanical mastery stage with minimal margin for drift.',
  journeyNote: 'The campaign dives underground into a canyon that behaves like a living trap.',
  bgColor: '#0e0707',
  accentColor: 0xff7a66,
  nebulaColor: 0x4d1f1c,
  nebulaAlpha: 0.13,
  colorGrade: { brightness: 0.02, contrast: 1.2, saturation: 0.97 },
  planetPalette: [0x7f3a2d, 0xd88372],
  enemies: [
    { type: 'fighter', weight: 33 },
    { type: 'bomber', weight: 16 },
    { type: 'swarm', weight: 24 },
    { type: 'gunship', weight: 27 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.08,
  levelDistance: 20000,
  hasBoss: true,
  boss: {
    name: 'Rift Basilisk',
    maxHp: 5300,
    phase1Cooldown: 720,
    phase2Cooldown: 320,
    phase2MoveSpeed: 252,
    phaseTransitionPauseMs: 220,
    attackStyle: 'pursuit',
    phase1SpreadShotCount: 8,
    phase1SpreadArcDegrees: 44,
    phase1BulletSpeedScale: 1.12,
    phase2SpiralShotCount: 7,
    phase2SpiralTurnRate: 136,
    phase2BulletSpeedScale: 1.2,
  },
  bossTriggerProgress: 0.61,
  asteroidInterval: 3000,
  sections: [
    {
      id: 'rift-scoutdown',
      label: 'Rift Mouth',
      startProgress: 0,
      endProgress: 0.13,
      phase: 'intro',
      summary: 'Open lane setup before canyon walls close in.',
      musicIntensity: 0.52,
      tensionArc: 'constant',
      vatTarget: { valence: -0.16, arousal: 0.56, tension: 0.52 },
    },
    {
      id: 'rift-descent',
      label: 'Descent Walls',
      startProgress: 0.13,
      endProgress: 0.32,
      phase: 'build',
      summary: 'Descent squeeze introduces corridor authority with periodic burst punishment for late pivots.',
      hazardEvents: [
        { type: 'rock-corridor', cadenceMs: 2020, corridorWidth: 188, laneCount: 2, damage: 1, intensity: 0.74 },
        { type: 'debris-surge', cadenceMs: 2660, intensity: 0.4 },
      ],
      musicIntensity: 0.7,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.22, arousal: 0.68, tension: 0.66 },
    },
    {
      id: 'rift-fracture-burst',
      label: 'Fracture Burst',
      startProgress: 0.32,
      endProgress: 0.49,
      phase: 'hazard',
      summary: 'Fracture lane sequence layers corridor bends, debris pressure, and mine traps as one cadence.',
      hazardEvents: [
        { type: 'rock-corridor', cadenceMs: 1880, corridorWidth: 182, laneCount: 2, damage: 1, intensity: 0.68 },
        { type: 'debris-surge', cadenceMs: 2200, intensity: 0.56 },
        { type: 'minefield', cadenceMs: 2480, intensity: 0.44 },
      ],
      musicIntensity: 0.84,
      tensionArc: 'waves',
      vatTarget: { valence: -0.28, arousal: 0.8, tension: 0.8 },
    },
    {
      id: 'rift-lock',
      label: 'Lockjaw Corridor',
      startProgress: 0.49,
      endProgress: 0.59,
      phase: 'climax',
      summary: 'Lockjaw finale seals fallback lines with chained corridor clamps and pursuit pull traps.',
      spawnRateMultiplier: 2.14,
      hazardEvents: [
        { type: 'rock-corridor', cadenceMs: 1720, corridorWidth: 176, laneCount: 3, damage: 1, intensity: 0.84 },
        { type: 'gravity-well', cadenceMs: 1980, intensity: 0.68 },
        { type: 'debris-surge', cadenceMs: 2320, intensity: 0.5 },
      ],
      musicIntensity: 0.96,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.34, arousal: 0.92, tension: 0.92 },
    },
    {
      id: 'rift-basilisk',
      label: 'Predator Chamber',
      startProgress: 0.59,
      endProgress: 0.61,
      phase: 'boss-approach',
      summary: 'A narrow calm announces the canyon apex predator.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 4700,
      musicIntensity: 0.86,
      tensionArc: 'constant',
      vatTarget: { valence: -0.1, arousal: 0.5, tension: 0.56 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Rift Pressure',
    bossCueName: 'Rift Pressure: Basilisk Chase',
    mood: 'claustrophobic urgency and predatory dread',
    tempoFeel: 'compressed pulse with sharp acceleration',
    style: 'dark chromatic motifs over relentless low-end chase rhythm',
    intensity: 'extreme',
    shifts: ['Lockjaw corridor adds relentless chromatic motion and faster accent cycling.'],
    tempo: 116,
    rootHz: 82.41,
    patternRoot: 0,
    bassPattern: bassPatterns.mawChase,
    pulsePattern: arpeggiatorPatterns.claustrophobicTight,
    leadPattern: arpeggiatorPatterns.ominousDrift,
    bossBassPattern: bassPatterns.chromaticPulse,
    bossPulsePattern: arpeggiatorPatterns.darkChromatic,
    bossLeadPattern: arpeggiatorPatterns.stalkingPursuit,
    bossTempo: 126,
    intent: {
      deterministicSeed: 'obsidian-maw-rift-pressure',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'phrygian',
        chordProgressionTags: ['low-pedal-grind', 'chromatic-crawl'],
        rhythmicFeel: 'compressed pursuit swing',
        energyProfile: { baseline: 0.58, peak: 0.97, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'locrian',
        chordProgressionTags: ['predator-rise', 'dissonant-rift-hit'],
        rhythmicFeel: 'relentless lockjaw chase',
        energyProfile: { baseline: 0.78, peak: 1, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'diminished' },
            { degree: 2, barsDuration: 1, quality: 'minor' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'diminished' },
          ],
        },
      },
    },
  }),
};
