import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../music';
import { createSignatureMusic } from './reimaginedMusic';

export const OBSIDIAN_MAW_LEVEL: LevelConfig = {
  name: 'Swarmfront',
  planetName: 'Hive Lathe',
  destination: 'Hive foundries of Hive Lathe',
  visualTheme: 'Acid-green honeycomb swarms over amber industrial haze.',
  coreGameplayIdea: 'A swarm survival set-piece where splitters return and density peaks.',
  pacingSummary: 'Escalating swarm fronts crest into the Hive Maelstrom vortex.',
  enemyCompositionSummary: 'Swarms flood; splitters multiply; dodgers and fighters harry.',
  hazardSummary: 'Debris surges and ring crossfire woven through swarm fronts.',
  bossConcept: 'Hive Maelstrom debuts the maelstrom style with counter-rotating spirals.',
  difficultyRole: 'Hard set-piece with maximum density before the finale.',
  journeyNote: 'The hive never stops; survival is the only objective.',
  bgColor: '#0a1006',
  accentColor: 0xb8f75a,
  nebulaColor: 0x2c3c12,
  nebulaAlpha: 0.13,
  colorGrade: { brightness: 0.06, contrast: 1.12, saturation: 1.05 },
  planetPalette: [0x5c8f1f, 0xe2f5a8],
  enemies: [
    { type: 'swarm', weight: 45 },
    { type: 'splitter', weight: 15 },
    { type: 'dodger', weight: 15 },
    { type: 'fighter', weight: 25 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.1,
  levelDistance: 20000,
  hasBoss: true,
  boss: {
    name: 'Hive Maelstrom',
    maxHp: 2300,
    phase1Cooldown: 880,
    phase2Cooldown: 440,
    phase2MoveSpeed: 190,
    phaseTransitionPauseMs: 280,
    attackStyle: 'maelstrom',
    phase1SpreadShotCount: 7,
    phase1SpreadArcDegrees: 64,
    phase1BulletSpeedScale: 1,
    phase2SpiralShotCount: 7,
    phase2SpiralTurnRate: 112,
    phase2BulletSpeedScale: 1.08,
    guardCapacity: 50,
    guardDecayDelayMs: 1200,
    guardDecayPerSecond: 18,
    guardBreakDurationMs: 1800,
  },
  bossAddWaves: true,
  lastLifeHelperWing: {
    shipCount: 2,
    helperLives: 2,
    hpScaleFromPlayer: 0.5,
    fireRateMs: 250,
    respawnDelayMs: 760,
    spacing: 36,
    followOffsetY: 18,
  },
  bossTriggerProgress: 0.68,
  asteroidInterval: 3000,
  sections: [
    {
      id: 'hive-perimeter',
      label: 'Hive Perimeter',
      startProgress: 0,
      endProgress: 0.13,
      phase: 'intro',
      summary: 'The hive perimeter stirs: thin swarm lines probe the lanes before the density climbs.',
      waves: [
        {
          id: 'perimeter-skimmers',
          atMs: 2500,
          formation: 'line',
          type: 'swarm',
          count: 5,
          lane: 3,
          telegraph: 'warning',
          notes: 'First skimmers of the brood read as a thin, warned line.',
        },
        {
          id: 'perimeter-pair',
          atMs: 9000,
          formation: 'column',
          type: 'fighter',
          count: 2,
          lane: 2,
          telegraph: 'warning',
          notes: 'A fighter pair rides the perimeter behind the skimmer line.',
        },
      ],
      musicIntensity: 0.5,
      tensionArc: 'constant',
      vatTarget: { valence: -0.16, arousal: 0.56, tension: 0.52 },
    },
    {
      id: 'first-brood',
      label: 'First Brood',
      startProgress: 0.13,
      endProgress: 0.32,
      phase: 'build',
      summary: 'First brood rings teach swarm survival: read the ring, carve a lane, clear fast for the bonus brood.',
      hazardEvents: [
        { type: 'debris-surge', cadenceMs: 2800, intensity: 0.5 },
      ],
      waves: [
        {
          id: 'brood-ring-one',
          atMs: 3000,
          formation: 'ring',
          type: 'swarm',
          count: 6,
          lane: 3,
          telegraph: 'warning',
          notes: 'First swarm ring; density is the lesson here.',
        },
        {
          id: 'brood-pincer-bonus',
          atMs: 11000,
          formation: 'pincer',
          type: 'swarm',
          count: 6,
          telegraph: 'warning',
          bonusOnClearMs: 4000,
          bonusWave: { type: 'swarm', count: 4 },
          notes: 'Clear the pincer fast and the hive answers with a bonus brood.',
        },
        {
          id: 'splitter-pack-one',
          atMs: 19000,
          formation: 'vee',
          type: 'splitter',
          count: 2,
          lane: 3,
          aceCount: 1,
          telegraph: 'warning',
          notes: 'Splitter pack: every kill multiplies into swarmlings; the gilded ace point is the priority read before it splits.',
        },
      ],
      musicIntensity: 0.68,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.22, arousal: 0.68, tension: 0.66 },
    },
    {
      id: 'brood-surge',
      label: 'Brood Surge',
      startProgress: 0.32,
      endProgress: 0.5,
      phase: 'hazard',
      summary: 'The brood surges: debris and ring-crossfire weave through the swarm front while splitters multiply the pressure.',
      hazardEvents: [
        { type: 'debris-surge', cadenceMs: 2600, intensity: 0.55 },
        { type: 'ring-crossfire', cadenceMs: 3400, intensity: 0.5 },
      ],
      waves: [
        {
          id: 'dodger-harry-hive',
          atMs: 2000,
          formation: 'column',
          type: 'dodger',
          count: 3,
          lane: 1,
          telegraph: 'warning',
          notes: 'Dodgers harry the edge lanes while the brood floods center.',
        },
        {
          id: 'brood-ring-two',
          atMs: 9000,
          formation: 'ring',
          type: 'swarm',
          count: 8,
          lane: 4,
          telegraph: 'warning',
          notes: 'A wider swarm ring lands off-center; carve a lane through it.',
        },
        {
          id: 'splitter-pack-two',
          atMs: 16000,
          formation: 'line',
          type: 'splitter',
          count: 3,
          lane: 3,
          telegraph: 'warning',
          notes: 'Splitter pack behind the ring; kills multiply under crossfire.',
        },
      ],
      recoveryDrops: [
        {
          id: 'brood-health-relief',
          triggerProgress: 0.7,
          type: 'health',
          lane: 'center',
          notes: 'Relief beat at the heat front: a breath before the crest.',
        },
      ],
      musicIntensity: 0.82,
      tensionArc: 'waves',
      vatTarget: { valence: -0.28, arousal: 0.8, tension: 0.8 },
    },
    {
      id: 'maelstrom-vanguard',
      label: 'Maelstrom Vanguard',
      startProgress: 0.5,
      endProgress: 0.66,
      phase: 'climax',
      summary: 'Density peaks at the crest: swarm pincers and the fighter honor guard escort the Maelstrom vanguard.',
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 2.16,
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 2400, intensity: 0.6 },
        { type: 'debris-surge', cadenceMs: 3100, intensity: 0.55 },
      ],
      waves: [
        {
          id: 'density-crest-pincer',
          atMs: 1500,
          formation: 'pincer',
          type: 'swarm',
          count: 8,
          telegraph: 'warning',
          bonusOnClearMs: 4000,
          bonusWave: { type: 'swarm', count: 4 },
          notes: 'Density crest; fast clears earn a relief bonus brood.',
        },
        {
          id: 'fighter-screen',
          atMs: 7000,
          formation: 'vee',
          type: 'fighter',
          count: 4,
          lane: 3,
          telegraph: 'warning',
          notes: 'Fighter screen vee sweeps the lanes ahead of the honor guard.',
        },
        {
          id: 'hive-elite-beat',
          atMs: 14000,
          formation: 'vee',
          type: 'fighter',
          count: 5,
          lane: 3,
          aceCount: 1,
          telegraph: 'warning',
          midBossBeat: true,
          notes: 'Mid-boss elite wave: the hive honor guard answers the crest; the gilded ace point leads the guard.',
        },
      ],
      musicIntensity: 0.96,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.34, arousal: 0.92, tension: 0.92 },
    },
    {
      id: 'hive-hush',
      label: 'Hive Hush',
      startProgress: 0.66,
      endProgress: 0.68,
      phase: 'boss-approach',
      summary: 'A sudden hush in the hive: one thin brood, a shield relief beat, then the Maelstrom.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 4700,
      waves: [
        {
          id: 'last-brood',
          atMs: 400,
          formation: 'line',
          type: 'swarm',
          count: 4,
          lane: 3,
          telegraph: 'warning',
          notes: 'A thin final brood before the Maelstrom; a breath, not a wall.',
        },
      ],
      recoveryDrops: [
        {
          id: 'maelstrom-shield-relief',
          triggerProgress: 0.45,
          type: 'shield',
          lane: 'center',
          notes: 'Pre-boss relief beat: shield up before the Hive Maelstrom spins up.',
        },
      ],
      musicIntensity: 0.86,
      tensionArc: 'constant',
      vatTarget: { valence: -0.1, arousal: 0.5, tension: 0.56 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Hive Surge',
    bossCueName: 'Hive Surge: Hive Maelstrom',
    mood: 'swarming claustrophobia with acidic drive',
    tempoFeel: 'relentless swarm rush',
    style: 'acid synth swarm over pounding hive drums',
    intensity: 'extreme',
    shifts: ['Hive swarm fronts add relentless chromatic motion and faster accent cycling.'],
    tempo: 122,
    rootHz: 69.3,
    patternRoot: 0,
    bassPattern: bassPatterns.mawChase,
    pulsePattern: arpeggiatorPatterns.claustrophobicTight,
    leadPattern: arpeggiatorPatterns.ominousDrift,
    bossBassPattern: bassPatterns.chromaticPulse,
    bossPulsePattern: arpeggiatorPatterns.darkChromatic,
    bossLeadPattern: arpeggiatorPatterns.stalkingPursuit,
    bossTempo: 126,
    intent: {
      deterministicSeed: 'swarmfront-hive-surge',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'phrygian',
        chordProgressionTags: ['low-pedal-grind', 'chromatic-crawl'],
        rhythmicFeel: 'compressed pursuit swing',
        energyProfile: { baseline: 0.58, peak: 0.97, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'locrian',
        chordProgressionTags: ['predator-rise', 'dissonant-rift-hit'],
        rhythmicFeel: 'relentless lockjaw chase',
        energyProfile: { baseline: 0.78, peak: 1, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'diminished' },
            { degree: 2, barsDuration: 1, quality: 'minor' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'diminished' },
          ],
        },
      },
    },
  }),
};
