import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets } from '../musicHelpers';

export const OBSIDIAN_MAW_LEVEL: LevelConfig = {
  name: 'Obsidian Maw',
  planetName: 'Kharon Rift',
  destination: 'A shattered moon canyon at Kharon Rift',
  visualTheme: 'Black rock walls, ember seams, and claustrophobic canyon lighting.',
  coreGameplayIdea: 'A standout canyon flight where the player threads damaging rock corridors under controlled enemy pressure.',
  pacingSummary: 'Open approach, then a long canyon gauntlet, then a predator boss in the exit chamber.',
  enemyCompositionSummary: 'Fighters and swarms harass movement while gunships guard the corridor exit.',
  hazardSummary: 'Rock corridor walls, falling debris, and tight navigation windows.',
  bossConcept: 'A drilling canyon hunter that chases the player with rotating lane denial.',
  difficultyRole: 'Signature navigation challenge and one of the campaign’s major set pieces.',
  journeyNote: 'The route narrows into a shattered moon whose canyon becomes the run’s most memorable piloting test.',
  bgColor: '#0f0705',
  accentColor: 0xff8a52,
  nebulaColor: 0x5e2415,
  nebulaAlpha: 0.08,
  colorGrade: { brightness: 0.01, contrast: 1.2, saturation: 1.1 },
  planetPalette: [0x6e3b24, 0xb86c41],
  enemies: [
    { type: 'scout', weight: 6 },
    { type: 'fighter', weight: 30 },
    { type: 'bomber', weight: 12 },
    { type: 'swarm', weight: 22 },
    { type: 'gunship', weight: 30 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.18,
  levelDistance: 14400,
  hasBoss: true,
  boss: {
    name: 'Maw Serpent',
    maxHp: 108,
    phase1Cooldown: 790,
    phase2Cooldown: 360,
    phase2MoveSpeed: 238,
    attackStyle: 'pursuit',
    phase1SpreadShotCount: 8,
    phase1SpreadArcDegrees: 58,
    phase1BulletSpeedScale: 1.08,
    phase2SpiralShotCount: 6,
    phase2SpiralTurnRate: 124,
    phase2BulletSpeedScale: 1.12,
  },
  bossTriggerProgress: 0.62,
  asteroidInterval: 3200,
  sections: [
    {
      id: 'maw-approach',
      label: 'Cracked Approach',
      startProgress: 0,
      endProgress: 0.2,
      phase: 'build',
      summary: 'The player sees the moon break apart ahead while enemy patrols herd them inward.',
      enemyFocus: [
        { type: 'scout', weight: 22 },
        { type: 'fighter', weight: 60 },
        { type: 'gunship', weight: 18 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.9,
      musicIntensity: 0.5,
    },
    {
      id: 'maw-corridor',
      label: 'Obsidian Corridor',
      startProgress: 0.2,
      endProgress: 0.58,
      phase: 'hazard',
      summary: 'The canyon walls squeeze the safe lane while controlled enemy pressure keeps the section tense but fair.',
      enemyFocus: [
        { type: 'fighter', weight: 44 },
        { type: 'swarm', weight: 30 },
        { type: 'gunship', weight: 26 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 2.08,
      asteroidInterval: 4500,
      hazardEvents: [
        { type: 'rock-corridor', cadenceMs: 1650, corridorWidth: 208, laneCount: 2, damage: 1, intensity: 1 },
        { type: 'debris-surge', cadenceMs: 2400, intensity: 0.5 },
      ],
      musicIntensity: 0.92,
    },
    {
      id: 'maw-exit',
      label: 'Exit Chamber',
      startProgress: 0.58,
      endProgress: 0.62,
      phase: 'boss-approach',
      summary: 'The canyon opens just long enough to frame the hunter boss arrival.',
      musicIntensity: 1,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Maw Dive',
      mood: 'claustrophobic focus',
      tempoFeel: 'tight and stalking',
      musicalStyle: 'canyon rumble drone with clipped echo-stabs and close-mic grit',
      intensity: 'high',
      shiftMoments: ['The corridor adds more echo-stab activity and low dust rumble.', 'Boss variation escalates by tightening the pursuit texture and response phrases.'],
      bossCueName: 'Maw Dive: Serpent Wake',
    },
    {
      tempo: 132,
      rootHz: 103.83,
      stepsPerBeat: 4,
      masterGain: 1.0,
      expression: {
        ...trackExpressionPresets.subtleWidth,
        accent: { amount: 0.14, patternBias: 0.26, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sawtooth',
        pattern: [0, null, null, 0, 3, null, null, 5, 7, null, null, 8, 10, null, null, 12],
        gain: 0.19,
        durationSteps: 2,
        filterHz: 820,
        expression: {
          ...layerExpressionPresets.pad,
          accent: { ...layerExpressionPresets.gentleAccent.accent, emphasisSteps: [0, 3, 8, 12] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: [null, 12, null, 15, null, 15, null, null, 19, null, 19, null, null, 15, 12, null],
        gain: 0.048,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1700,
        expression: {
          ...layerExpressionPresets.pluck,
          accent: { ...layerExpressionPresets.drivingAccent.accent, emphasisSteps: [1, 3, 5, 8, 10, 14] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: [24, null, 22, null, 24, null, 27, null, 29, null, 27, null, 24, null, 22, null],
        gain: 0.038,
        durationSteps: 2,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.swell,
          ...layerExpressionPresets.drift,
          ...layerExpressionPresets.vibrato,
        },
      },
      noise: {
        pattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
        gain: 0.016,
        filterHz: 1300,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.rumble,
        },
      },
    },
    {
      tempo: 138,
      masterGain: 1.08,
      expression: {
        ...trackExpressionPresets.subtleWidth,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 300, rateHz: 1.18 },
        accent: { amount: 0.2, patternBias: 0.42, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { gain: 0.21, filterHz: 950 },
      pulse: {
        waveform: 'square',
        pattern: [12, null, 12, 15, null, 15, 17, null, 19, null, 19, 17, null, 15, 12, null],
        gain: 0.058,
      },
      lead: { waveform: 'triangle', gain: 0.044, filterHz: 1650 },
      noise: {
        gain: 0.021,
        filterHz: 1900,
        expression: {
          ...noiseExpressionPresets.grit,
        },
      },
    }
  ),
};
