import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets, arpeggiatorPatterns, bassPatterns } from '../musicHelpers';

export const TERMINUS_BLACK_LEVEL: LevelConfig = {
  name: 'Terminus Black',
  planetName: 'Acheron Gate',
  destination: 'The anomaly gate beyond known space',
  visualTheme: 'Near-black void, fracture light, and warped stars bending into a singularity.',
  coreGameplayIdea: 'A final approach where gravity distortions, elite waves, and a multi-role boss create a climax of everything learned.',
  pacingSummary: 'An ominous quiet, then escalating anomaly hazards, then a final overwhelming duel.',
  enemyCompositionSummary: 'Elite mixed roster with fast, coordinated attack windows.',
  hazardSummary: 'Gravity wells, anomaly surges, and the highest sustained pressure in the game.',
  bossConcept: 'A null-crown gate sentinel with shields, chase phases, rotating denial, and summoned escorts.',
  difficultyRole: 'Final test of route reading, positioning, and composure.',
  journeyNote: 'The journey ends at a gate that feels less like a destination and more like a threshold into the unknown.',
  bgColor: '#05050b',
  accentColor: 0x8aa6ff,
  nebulaColor: 0x1a2354,
  nebulaAlpha: 0.14,
  colorGrade: { brightness: 0.01, contrast: 1.22, saturation: 0.98 },
  planetPalette: [0x34447f, 0x6d84d7],
  enemies: [
    { type: 'scout', weight: 3 },
    { type: 'fighter', weight: 32 },
    { type: 'bomber', weight: 14 },
    { type: 'swarm', weight: 19 },
    { type: 'gunship', weight: 32 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.26,
  levelDistance: 15000,
  hasBoss: true,
  boss: {
    name: 'Null Crown',
    maxHp: 120,
    phase1Cooldown: 760,
    phase2Cooldown: 350,
    phase2MoveSpeed: 248,
    attackStyle: 'bulwark',
    phase1SpreadShotCount: 9,
    phase1SpreadArcDegrees: 74,
    phase1BulletSpeedScale: 1.1,
    phase2SpiralShotCount: 6,
    phase2SpiralTurnRate: 132,
    phase2BulletSpeedScale: 1.16,
  },
  bossTriggerProgress: 0.6,
  asteroidInterval: 3400,
  sections: [
    {
      id: 'terminus-silence',
      label: 'Dark Approach',
      startProgress: 0,
      endProgress: 0.16,
      phase: 'intro',
      summary: 'A deceptive hush before the anomaly starts folding in around the player.',
      enemyFocus: [
        { type: 'fighter', weight: 62 },
        { type: 'gunship', weight: 24 },
        { type: 'bomber', weight: 14 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.88,
      musicIntensity: 0.32,
    },
    {
      id: 'terminus-distortion',
      label: 'Anomaly Tides',
      startProgress: 0.16,
      endProgress: 0.6,
      phase: 'climax',
      summary: 'Gravity distortions and elite waves constantly reframe the safest lane.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 16 },
        { type: 'swarm', weight: 18 },
        { type: 'gunship', weight: 32 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 2.22,
      hazardEvents: [
        { type: 'gravity-well', cadenceMs: 2200, intensity: 0.82 },
        { type: 'energy-storm', cadenceMs: 1900, intensity: 0.66 },
      ],
      musicIntensity: 0.95,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Event Horizon Vector',
      mood: 'ominous awe with haunting melody',
      tempoFeel: 'suspended orbit pulling inward',
      musicalStyle: 'cosmic low-end bloom with distant beacon tones and a grave breathing noise bed',
      intensity: 'high with a restrained, melodic opening',
      shiftMoments: ['Early space leaves the motif intentionally hollow.', 'Anomaly tides add a steady counterpulse under the void tones.', 'Boss cue escalates by layering texture, width, and pressure around the same motif.'],
      bossCueName: 'Event Horizon Vector: Null Crown',
    },
    {
      tempo: 96,
      rootHz: 82.41,
      stepsPerBeat: 4,
      masterGain: 0.86,
      expression: {
        ...trackExpressionPresets.gentleFlow,
        stereo: { ...trackExpressionPresets.gentleFlow.stereo, width: 0.45, rateHz: 0.05, phaseOffset: 0.3 },
        accent: { amount: 0.06, patternBias: 0.12, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sine',
        pattern: bassPatterns.drone(0),
        gain: 0.14,
        durationSteps: 4,
        expression: {
          ...layerExpressionPresets.longPad,
          ...layerExpressionPresets.etherialGlow,
          accent: { ...layerExpressionPresets.breathPulse.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.ambientSparse(12),
        gain: 0.028,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1400,
        expression: {
          ...layerExpressionPresets.softPluck,
          ...layerExpressionPresets.wideSpace,
          accent: { amount: 0.06, patternBias: 0.1, emphasisSteps: [2, 5, 8, 13] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.upDownTriad(24),
        gain: 0.026,
        durationSteps: 4,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.slowSwell,
          ...layerExpressionPresets.wideSpace,
          ...layerExpressionPresets.gentleVibrato,
        },
      },
      noise: {
        pattern: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        gain: 0.01,
        filterHz: 1100,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.softAir,
          stereo: { ...noiseExpressionPresets.softAir.stereo, width: 0.3, rateHz: 0.04 },
        },
      },
    },
    {
      tempo: 104,
      masterGain: 0.94,
      expression: {
        ...trackExpressionPresets.gentleFlow,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 200, rateHz: 0.8 },
        accent: { amount: 0.14, patternBias: 0.26, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { waveform: 'triangle', gain: 0.16, filterHz: 900 },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.flowing(12),
        gain: 0.04,
        filterHz: 1750,
      },
      lead: { waveform: 'sine', gain: 0.034 },
      noise: {
        gain: 0.013,
        filterHz: 1600,
        expression: {
          ...noiseExpressionPresets.rumble,
          accent: { amount: 0.08, patternBias: 0.16, emphasisSteps: [3, 7, 11, 15] },
        },
      },
    }
  ),
};
