import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const TERMINUS_BLACK_LEVEL: LevelConfig = {
  name: 'Eventide Singularity',
  planetName: 'Acheron Apex',
  destination: 'Terminal singularity threshold beyond Acheron Apex',
  visualTheme: 'Near-black vacuum broken by cobalt fracture light and warped stellar halos.',
  coreGameplayIdea: 'Final convergence stage where learned hazard grammars overlap in controlled overload patterns.',
  pacingSummary: 'False calm, anomaly lattice, convergence overload, and final sovereign duel.',
  enemyCompositionSummary: 'Elite mixed roster with constant role overlap and minimal downtime.',
  hazardSummary: 'Layered anomaly overlap: ring sweeps, pull traps, storm bursts, and debris punctuation in planned waves.',
  bossConcept: 'Axiom Null cycles bulwark denial, chase pressure, and spiral collapse patterns.',
  difficultyRole: 'Ultimate composure and adaptation exam.',
  journeyNote: 'The run closes at a threshold where space itself feels actively hostile.',
  bgColor: '#05060d',
  accentColor: 0x9eb5ff,
  nebulaColor: 0x1c2b61,
  nebulaAlpha: 0.15,
  colorGrade: { brightness: 0.01, contrast: 1.24, saturation: 0.96 },
  planetPalette: [0x43589f, 0x9eb5ff],
  enemies: [
    { type: 'fighter', weight: 31 },
    { type: 'bomber', weight: 16 },
    { type: 'swarm', weight: 20 },
    { type: 'gunship', weight: 33 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 2.24,
  levelDistance: 20800,
  hasBoss: true,
  boss: {
    name: 'Axiom Null',
    maxHp: 6400,
    phase1Cooldown: 760,
    phase2Cooldown: 300,
    phase2MoveSpeed: 248,
    phaseTransitionPauseMs: 420,
    attackStyle: 'bulwark',
    phase1SpreadShotCount: 10,
    phase1SpreadArcDegrees: 86,
    phase1BulletSpeedScale: 1.14,
    phase2SpiralShotCount: 8,
    phase2SpiralTurnRate: 146,
    phase2BulletSpeedScale: 1.24,
  },
  lastLifeHelperWing: {
    shipCount: 2,
    helperLives: 2,
    hpScaleFromPlayer: 0.5,
    fireRateMs: 240,
    respawnDelayMs: 720,
    spacing: 34,
    followOffsetY: 18,
  },
  bossTriggerProgress: 0.59,
  asteroidInterval: 2900,
  sections: [
    {
      id: 'eventide-hush',
      label: 'Singularity Hush',
      startProgress: 0,
      endProgress: 0.11,
      phase: 'intro',
      summary: 'Quiet opening to amplify later escalation cues.',
      musicIntensity: 0.36,
      tensionArc: 'constant',
      vatTarget: { valence: -0.2, arousal: 0.5, tension: 0.5 },
    },
    {
      id: 'eventide-distort',
      label: 'Distortion Lattice',
      startProgress: 0.11,
      endProgress: 0.26,
      phase: 'build',
      summary: 'Distortion lattice starts the overlap language by pairing pulls with slow crossfire framing.',
      hazardEvents: [
        { type: 'gravity-well', cadenceMs: 2360, intensity: 0.63 },
        { type: 'ring-crossfire', cadenceMs: 2920, intensity: 0.34 },
      ],
      musicIntensity: 0.56,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.24, arousal: 0.66, tension: 0.66 },
    },
    {
      id: 'eventide-anomaly-rush',
      label: 'Anomaly Rush',
      startProgress: 0.26,
      endProgress: 0.43,
      phase: 'hazard',
      summary: 'Anomaly rush sequences stack storm, debris, and pull beats into adaptive lane puzzles.',
      hazardEvents: [
        { type: 'energy-storm', cadenceMs: 1880, intensity: 0.72 },
        { type: 'debris-surge', cadenceMs: 2080, intensity: 0.64 },
        { type: 'gravity-well', cadenceMs: 2460, intensity: 0.52 },
      ],
      musicIntensity: 0.84,
      tensionArc: 'waves',
      vatTarget: { valence: -0.3, arousal: 0.84, tension: 0.84 },
    },
    {
      id: 'eventide-convergence',
      label: 'Null Convergence',
      startProgress: 0.43,
      endProgress: 0.57,
      phase: 'climax',
      summary: 'Convergence overload merges all major hazard grammars in one sustained final exam.',
      spawnRateMultiplier: 2.26,
      encounterSizeOverride: { min: 2, max: 3 },
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 1600, intensity: 0.8 },
        { type: 'gravity-well', cadenceMs: 1780, intensity: 0.76 },
        { type: 'energy-storm', cadenceMs: 1740, intensity: 0.74 },
        { type: 'debris-surge', cadenceMs: 2100, intensity: 0.62 },
      ],
      musicIntensity: 0.97,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.38, arousal: 0.96, tension: 0.96 },
    },
    {
      id: 'eventide-axis',
      label: 'Axiom Gate',
      startProgress: 0.57,
      endProgress: 0.59,
      phase: 'boss-approach',
      summary: 'Final warning lane before the campaign sovereign manifests.',
      spawnRateMultiplier: 0.9,
      asteroidInterval: 4800,
      musicIntensity: 0.88,
      tensionArc: 'constant',
      vatTarget: { valence: -0.12, arousal: 0.54, tension: 0.6 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Eventide Threshold',
    bossCueName: 'Eventide Threshold: Axiom Null',
    mood: 'cosmic dread resolving into focused defiance',
    tempoFeel: 'slow gravitational draw then catastrophic acceleration',
    style: 'void drones, chromatic pressure figures, and final confrontation ostinato',
    intensity: 'maximum',
    shifts: ['Convergence phase removes breathing gaps and drives continuous accent pressure.'],
    tempo: 112,
    rootHz: 82.41,
    patternRoot: 0,
    bassPattern: bassPatterns.voidStalker,
    pulsePattern: arpeggiatorPatterns.cosmicVastness,
    leadPattern: arpeggiatorPatterns.voidBeacon,
    bossBassPattern: bassPatterns.finalBossOstinato,
    bossPulsePattern: arpeggiatorPatterns.darkChromatic,
    bossLeadPattern: arpeggiatorPatterns.tensionMaximum,
    bossTempo: 128,
    bossGain: 1.1,
    intent: {
      deterministicSeed: 'terminus-black-eventide-threshold',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'aeolian',
        chordProgressionTags: ['void-drone-pedal', 'catastrophic-tilt'],
        rhythmicFeel: 'gravitational draw with fracture accents',
        energyProfile: { baseline: 0.62, peak: 0.99, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 6, barsDuration: 1, quality: 'major' },
            { degree: 3, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'major' },
          ],
        },
      },
      boss: {
        mode: 'ultralocrian',
        chordProgressionTags: ['final-sovereign-ostinato', 'chromatic-collapse'],
        rhythmicFeel: 'continuous catastrophe drive',
        energyProfile: { baseline: 0.84, peak: 1, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'diminished' },
            { degree: 2, barsDuration: 1, quality: 'minor' },
            { degree: 5, barsDuration: 1, quality: 'diminished' },
            { degree: 1, barsDuration: 1, quality: 'diminished' },
          ],
        },
      },
    },
  }),
};
