import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../music';
import { createSignatureMusic } from './reimaginedMusic';

export const WARZONE_CORRIDOR_LEVEL: LevelConfig = {
  name: 'Clockwork Causeway',
  planetName: 'Gearhaven',
  destination: 'Clockwork transit causeway around Gearhaven',
  visualTheme: 'Brass gearwork silhouettes and metronomic signal lamps over a sepia void.',
  coreGameplayIdea: 'Waves arrive on the musical beat while lancers debut telegraphed sniper duels.',
  pacingSummary: 'Metronomic encounters escalate into pressure patterns and the Marshal duel.',
  enemyCompositionSummary: 'Fighters and gunships hold tempo; lancers debut as elite duelists; divers punctuate.',
  hazardSummary: 'Timed debris and crossfire beats synced to the clockwork rhythm.',
  bossConcept: 'Marshal Vectra presses forward with pressure patterns behind a disciplined advance.',
  difficultyRole: 'Ramp level introducing elite telegraph discipline.',
  journeyNote: 'Every gear of Gearhaven turns on the beat; so do its defenders.',
  bgColor: '#100c06',
  accentColor: 0xf7c86a,
  nebulaColor: 0x4a3a14,
  nebulaAlpha: 0.12,
  colorGrade: { brightness: 0.07, contrast: 1.1, saturation: 0.98 },
  planetPalette: [0x8f6f2a, 0xf5e2a8],
  enemies: [
    { type: 'fighter', weight: 30 },
    { type: 'lancer', weight: 20 },
    { type: 'diver', weight: 20 },
    { type: 'gunship', weight: 30 },
  ],
  encounterSize: { min: 2, max: 2 },
  spawnRateMultiplier: 1.55,
  levelDistance: 16000,
  hasBoss: true,
  boss: {
    name: 'Marshal Vectra',
    maxHp: 1700,
    phase1Cooldown: 940,
    phase2Cooldown: 470,
    phase2MoveSpeed: 195,
    phaseTransitionPauseMs: 280,
    attackStyle: 'pressure',
    phase1SpreadShotCount: 7,
    phase1SpreadArcDegrees: 58,
    phase1BulletSpeedScale: 0.98,
    phase2SpiralShotCount: 5,
    phase2SpiralTurnRate: 94,
    phase2BulletSpeedScale: 1.05,
  },
  bossTriggerProgress: 0.7,
  asteroidInterval: 3600,
  sections: [
    {
      id: 'convoy-vanguard',
      label: 'Vanguard Sweep',
      startProgress: 0,
      endProgress: 0.16,
      phase: 'intro',
      summary: 'Fighter packets arrive on the musical beat, setting the metronome for the causeway.',
      musicIntensity: 0.5,
      tensionArc: 'constant',
      vatTarget: { valence: -0.08, arousal: 0.52, tension: 0.44 },
    },
    {
      id: 'convoy-railfire',
      label: 'Railfire',
      startProgress: 0.16,
      endProgress: 0.34,
      phase: 'build',
      summary: 'Lancers debut with telegraphed sniper duels while crossfire tracers mark the beat.',
      hazardEvents: [
        { type: 'ring-crossfire', cadenceMs: 1980, intensity: 0.6 },
        { type: 'debris-surge', cadenceMs: 2440, intensity: 0.42 },
      ],
      waves: [
        {
          id: 'l4-lancer-debut',
          atMs: 4000,
          formation: 'column',
          type: 'lancer',
          count: 2,
          lane: 3,
          telegraph: 'warning',
          notes: 'Lancer debut on the beat: a warned sniper column, one telegraphed bolt each, readable duel.',
        },
      ],
      spawnRateMultiplier: 1.62,
      musicIntensity: 0.66,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.14, arousal: 0.62, tension: 0.58 },
    },
    {
      id: 'convoy-pocket-mines',
      label: 'Escapement Pockets',
      startProgress: 0.34,
      endProgress: 0.53,
      phase: 'hazard',
      summary: 'Bait lanes collapse into gear-trap pockets when pilots over-hold center; every collapse is telegraphed on the tick.',
      asteroidInterval: 3200,
      hazardEvents: [
        { type: 'debris-surge', cadenceMs: 2200, intensity: 0.5 },
        { type: 'ring-crossfire', cadenceMs: 2800, intensity: 0.48 },
      ],
      waves: [
        {
          id: 'l4-lancer-pocket-duel',
          atMs: 4000,
          formation: 'column',
          type: 'lancer',
          count: 1,
          lane: 4,
          telegraph: 'warning',
          notes: 'A single lancer holds high on the beat, punishing center holds with a telegraphed bolt.',
        },
        {
          id: 'l4-diver-vee-tick',
          atMs: 8000,
          formation: 'vee',
          type: 'diver',
          count: 3,
          lane: 2,
          telegraph: 'none',
          notes: 'Diver vee lands two ticks later to punctuate the pocket collapse.',
        },
      ],
      musicIntensity: 0.78,
      tensionArc: 'waves',
      vatTarget: { valence: -0.2, arousal: 0.72, tension: 0.7 },
    },
    {
      id: 'convoy-lock',
      label: 'Convoy Lock',
      startProgress: 0.53,
      endProgress: 0.68,
      phase: 'climax',
      summary: 'The causeway locks into narrow gear corridors as suppressive bursts arrive on the musical beat.',
      encounterSizeOverride: { min: 2, max: 3 },
      hazardEvents: [
        { type: 'rock-corridor', cadenceMs: 2020, corridorWidth: 205, laneCount: 2, damage: 1, intensity: 0.7 },
        { type: 'energy-storm', cadenceMs: 2580, intensity: 0.4 },
      ],
      waves: [
        {
          id: 'l4-gunship-midboss',
          atMs: 8000,
          formation: 'column',
          type: 'gunship',
          count: 2,
          lane: 3,
          telegraph: 'warning',
          midBossBeat: true,
          notes: 'Mid-boss elite wave on the beat: a warned gunship column before the Marshal presses in.',
        },
      ],
      musicIntensity: 0.88,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.26, arousal: 0.84, tension: 0.82 },
    },
    {
      id: 'convoy-command',
      label: 'Command Arrival',
      startProgress: 0.68,
      endProgress: 0.7,
      phase: 'boss-approach',
      summary: 'Siren lamps hush the gears for a breath before the Marshal presses the duel.',
      spawnRateMultiplier: 0.92,
      asteroidInterval: 5200,
      recoveryDrops: [
        {
          id: 'l4-shield-preboss',
          triggerProgress: 0.5,
          type: 'shield',
          lane: 'center',
          notes: 'Relief beat: a breather shield before Marshal Vectra so pilots stabilize at the gate.',
        },
      ],
      musicIntensity: 0.84,
      tensionArc: 'constant',
      vatTarget: { valence: -0.06, arousal: 0.46, tension: 0.52 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'Gear March',
    bossCueName: 'Gear March: Marshal Vectra',
    mood: 'precision discipline with mechanical swing',
    tempoFeel: 'metronomic march with tick accents',
    style: 'clockwork electro-march over brass-toned bass',
    intensity: 'high',
    shifts: ['Convoy lock thickens accents and drives an unbroken pursuit pulse.'],
    tempo: 112,
    rootHz: 92.5,
    patternRoot: 0,
    bassPattern: bassPatterns.powerChordBass,
    pulsePattern: arpeggiatorPatterns.powerChordArp,
    leadPattern: arpeggiatorPatterns.callResponse,
    bossBassPattern: bassPatterns.tensionWalkBass,
    bossPulsePattern: arpeggiatorPatterns.martialStomp,
    bossLeadPattern: arpeggiatorPatterns.tensionChromatic,
    bossTempo: 114,
    intent: {
      deterministicSeed: 'clockwork-causeway-gear-march',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'phrygian',
        chordProgressionTags: ['minor-pedal', 'quartal-command-voicing'],
        rhythmicFeel: 'forward military stomp',
        energyProfile: { baseline: 0.5, peak: 0.9, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'locrian',
        chordProgressionTags: ['chromatic-march', 'cluster-pressure'],
        rhythmicFeel: 'unbroken chase ostinato',
        energyProfile: { baseline: 0.7, peak: 0.96, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'diminished' },
            { degree: 2, barsDuration: 1, quality: 'minor' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'diminished' },
          ],
        },
      },
    },
  }),
};
