import type { LevelConfig } from '../types';
import { createMusicProfile } from '../musicHelpers';

export const WARZONE_CORRIDOR_LEVEL: LevelConfig = {
  name: 'Warzone Corridor',
  planetName: 'Antares Fortress',
  destination: 'Siege route to Antares Fortress',
  visualTheme: 'Red-brown battle haze, tracer-like accents, and ember clouds.',
  coreGameplayIdea: 'Constant frontal pressure with almost no free space.',
  pacingSummary: 'Immediate combat density, then hard sustain into the boss approach.',
  enemyCompositionSummary: 'Full mixed roster with heavy fighter and gunship presence.',
  hazardSummary: 'Frequent asteroids and crossfire-heavy encounter clusters.',
  bossConcept: 'A war carrier that locks the player into lane discipline and denial zones.',
  difficultyRole: 'Escalation from reactive play into intentional route carving.',
  journeyNote: 'The frontier now becomes an organized military blockade.',
  bgColor: '#180900',
  accentColor: 0xff4444,
  nebulaColor: 0x662211,
  nebulaAlpha: 0.10,
  colorGrade: { brightness: 0.03, contrast: 1.14, saturation: 1.24 },
  planetPalette: [0x886644, 0xaa8866],
  enemies: [
    { type: 'scout', weight: 20 },
    { type: 'fighter', weight: 25 },
    { type: 'bomber', weight: 20 },
    { type: 'swarm', weight: 15 },
    { type: 'gunship', weight: 20 },
  ],
  encounterSize: { min: 2, max: 2 },
  spawnRateMultiplier: 1.7,
  levelDistance: 10800,
  hasBoss: true,
  boss: {
    name: 'Siegebreaker Vaal',
    maxHp: 62,
    phase1Cooldown: 1000,
    phase2Cooldown: 500,
    phase2MoveSpeed: 175,
    attackStyle: 'carrier',
    phase1SpreadShotCount: 7,
    phase1SpreadArcDegrees: 52,
    phase1BulletSpeedScale: 0.98,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 88,
    phase2BulletSpeedScale: 1.02,
  },
  bossTriggerProgress: 0.68,
  asteroidInterval: 3500,
  sections: [
    {
      id: 'warzone-open',
      label: 'Kill Box',
      startProgress: 0,
      endProgress: 0.26,
      phase: 'build',
      summary: 'The level opens with immediate mixed waves and very little empty space.',
      musicIntensity: 0.58,
    },
    {
      id: 'warzone-grind',
      label: 'Attrition Push',
      startProgress: 0.26,
      endProgress: 0.68,
      phase: 'climax',
      summary: 'Gunships and bombers overlap to punish overcommitting to one lane.',
      asteroidInterval: 3000,
      hazardEvents: [{ type: 'debris-surge', cadenceMs: 1900, intensity: 0.7 }],
      musicIntensity: 0.82,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Crimson Intercept',
      mood: 'battle-ready aggression',
      tempoFeel: 'driving and martial',
      musicalStyle: 'urgent arcade bassline with clipped percussion-like noise hits',
      intensity: 'high',
      shiftMoments: ['Noise hits get busier during attrition sections.', 'Boss variation raises tempo and tightens the melodic loop.'],
      bossCueName: 'Crimson Intercept: Siegebreaker',
    },
    {
      tempo: 136,
      rootHz: 110,
      stepsPerBeat: 4,
      masterGain: 1.02,
      bass: {
        waveform: 'sawtooth',
        pattern: [0, null, 0, null, 7, null, 5, null, 10, null, 7, null, 12, null, 10, null],
        gain: 0.18,
        durationSteps: 2,
        filterHz: 1100,
      },
      pulse: {
        waveform: 'square',
        pattern: [12, null, 14, null, 12, null, 17, null, 19, null, 17, null, 14, null, 12, null],
        gain: 0.06,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 2400,
      },
      lead: {
        waveform: 'triangle',
        pattern: [24, null, null, 19, 24, null, null, 17, 22, null, null, 19, 24, null, null, 14],
        gain: 0.05,
        durationSteps: 2,
        octaveShift: 1,
      },
      noise: {
        pattern: [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0],
        gain: 0.02,
        filterHz: 2400,
        durationSteps: 1,
      },
    },
    {
      tempo: 148,
      masterGain: 1.12,
      bass: { gain: 0.2 },
      pulse: { gain: 0.07 },
      lead: { waveform: 'sawtooth', gain: 0.06 },
      noise: { gain: 0.024, filterHz: 2800 },
    }
  ),
};
