import type { LevelConfig } from '../types';
import { arpeggiatorPatterns, bassPatterns } from '../musicHelpers';
import { createSignatureMusic } from './reimaginedMusic';

export const WARZONE_CORRIDOR_LEVEL: LevelConfig = {
  name: 'Fracture Convoy',
  planetName: 'Kestrel Reach',
  destination: 'Broken convoy spine crossing Kestrel Reach',
  visualTheme: 'Amber military strobes over fractured carrier debris and tracer streaks.',
  coreGameplayIdea: 'Front-loaded threat lanes reward anticipation and punish center-line tunnel vision.',
  pacingSummary: 'Convoy intercept, pressure stack, corridor lock, then command duel.',
  enemyCompositionSummary: 'Fighters and gunships anchor frontal pressure while bombers enforce lane shifts.',
  hazardSummary: 'Crossfire sweeps, mine pockets, and narrow convoy corridors.',
  bossConcept: 'Marshal Bront commands layered frontal barrages with advancing denial arcs.',
  difficultyRole: 'Mid-campaign aggression step-up with limited breathing room.',
  journeyNote: 'The warzone turns open space into a marching wall that must be out-read, not out-tanked.',
  bgColor: '#150b08',
  accentColor: 0xff9154,
  nebulaColor: 0x6e2a1d,
  nebulaAlpha: 0.13,
  colorGrade: { brightness: 0.06, contrast: 1.14, saturation: 1.01 },
  planetPalette: [0xb65a39, 0xffb07d],
  enemies: [
    { type: 'fighter', weight: 38 },
    { type: 'bomber', weight: 24 },
    { type: 'swarm', weight: 12 },
    { type: 'gunship', weight: 26 },
  ],
  encounterSize: { min: 2, max: 2 },
  spawnRateMultiplier: 1.58,
  levelDistance: 16200,
  hasBoss: true,
  boss: {
    name: 'Marshal Bront',
    maxHp: 1700,
    phase1Cooldown: 980,
    phase2Cooldown: 520,
    phase2MoveSpeed: 188,
    attackStyle: 'pressure',
    phase1SpreadShotCount: 6,
    phase1SpreadArcDegrees: 66,
    phase1BulletSpeedScale: 0.95,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 84,
    phase2BulletSpeedScale: 1.02,
  },
  bossTriggerProgress: 0.7,
  asteroidInterval: 3600,
  sections: [
    {
      id: 'convoy-vanguard',
      label: 'Vanguard Sweep',
      startProgress: 0,
      endProgress: 0.16,
      phase: 'intro',
      summary: 'Fast fighter packets establish the stage speed language.',
      musicIntensity: 0.5,
      tensionArc: 'constant',
      vatTarget: { valence: -0.08, arousal: 0.52, tension: 0.44 },
    },
    {
      id: 'convoy-railfire',
      label: 'Railfire',
      startProgress: 0.16,
      endProgress: 0.34,
      phase: 'build',
      summary: 'Cross-lane asteroid sweeps and bombers force diagonal routing.',
      hazardEvents: [{ type: 'ring-crossfire', cadenceMs: 1980, intensity: 0.6 }],
      spawnRateMultiplier: 1.62,
      musicIntensity: 0.66,
      tensionArc: 'gradualBuild',
      vatTarget: { valence: -0.14, arousal: 0.62, tension: 0.58 },
    },
    {
      id: 'convoy-pocket-mines',
      label: 'Pocket Mines',
      startProgress: 0.34,
      endProgress: 0.53,
      phase: 'hazard',
      summary: 'Mine pockets interrupt frontal fights and punish greedy lines.',
      asteroidInterval: 3200,
      hazardEvents: [{ type: 'minefield', cadenceMs: 1900, intensity: 0.63 }],
      musicIntensity: 0.78,
      tensionArc: 'waves',
      vatTarget: { valence: -0.2, arousal: 0.72, tension: 0.7 },
    },
    {
      id: 'convoy-lock',
      label: 'Convoy Lock',
      startProgress: 0.53,
      endProgress: 0.68,
      phase: 'climax',
      summary: 'Narrow corridor pressure with coordinated gunship anchors.',
      encounterSizeOverride: { min: 2, max: 3 },
      hazardEvents: [{ type: 'rock-corridor', cadenceMs: 2050, corridorWidth: 205, laneCount: 2, damage: 1, intensity: 0.72 }],
      musicIntensity: 0.88,
      tensionArc: 'buildRelease',
      vatTarget: { valence: -0.26, arousal: 0.84, tension: 0.82 },
    },
    {
      id: 'convoy-command',
      label: 'Command Arrival',
      startProgress: 0.68,
      endProgress: 0.7,
      phase: 'boss-approach',
      summary: 'A short warning lull lets the command ship frame the boss stakes.',
      spawnRateMultiplier: 0.92,
      asteroidInterval: 5200,
      musicIntensity: 0.84,
      tensionArc: 'constant',
      vatTarget: { valence: -0.06, arousal: 0.46, tension: 0.52 },
    },
  ],
  music: createSignatureMusic({
    cueName: 'March of Fragments',
    bossCueName: 'March of Fragments: Bront Directive',
    mood: 'relentless military tension',
    tempoFeel: 'forward stomp with no idle beat',
    style: 'weighted bass ostinato with hard-edged sync pulse',
    intensity: 'high',
    shifts: ['Convoy lock thickens accents and drives an unbroken pursuit pulse.'],
    tempo: 106,
    rootHz: 92.5,
    patternRoot: 0,
    bassPattern: bassPatterns.powerChordBass,
    pulsePattern: arpeggiatorPatterns.powerChordArp,
    leadPattern: arpeggiatorPatterns.callResponse,
    bossBassPattern: bassPatterns.tensionWalkBass,
    bossPulsePattern: arpeggiatorPatterns.martialStomp,
    bossLeadPattern: arpeggiatorPatterns.tensionChromatic,
    bossTempo: 114,
    intent: {
      deterministicSeed: 'warzone-corridor-march-of-fragments',
      timeSignature: { beatsPerBar: 4, beatUnit: 4 },
      stage: {
        mode: 'phrygian',
        chordProgressionTags: ['minor-pedal', 'quartal-command-voicing'],
        rhythmicFeel: 'forward military stomp',
        energyProfile: { baseline: 0.5, peak: 0.9, curve: 'build' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'minor' },
            { degree: 2, barsDuration: 1, quality: 'major' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'minor' },
          ],
        },
      },
      boss: {
        mode: 'locrian',
        chordProgressionTags: ['chromatic-march', 'cluster-pressure'],
        rhythmicFeel: 'unbroken chase ostinato',
        energyProfile: { baseline: 0.7, peak: 0.96, curve: 'surge' },
        harmony: {
          steps: [
            { degree: 1, barsDuration: 1, quality: 'diminished' },
            { degree: 2, barsDuration: 1, quality: 'minor' },
            { degree: 7, barsDuration: 1, quality: 'minor' },
            { degree: 1, barsDuration: 1, quality: 'diminished' },
          ],
        },
      },
    },
  }),
};
