import type { LevelConfig } from '../types';
import { createMusicProfile } from '../musicHelpers';

export const WRECKFIELD_RUN_LEVEL: LevelConfig = {
  name: 'Wreckfield Run',
  planetName: 'Orpheus Relay',
  destination: 'A broken convoy graveyard around Orpheus Relay',
  visualTheme: 'Faded teal wreckage, drifting hull silhouettes, and salvage sparks.',
  coreGameplayIdea: 'Debris navigation with enemy ambushes from blind wreck angles.',
  pacingSummary: 'Calm salvage drift, then collapsing wreck channels, then a carrier fight.',
  enemyCompositionSummary: 'Fighters and gunships spearhead the pressure while scouts fill gaps.',
  hazardSummary: 'Wreck fragments, debris surges, and salvage choke lanes.',
  bossConcept: 'A salvage carrier that launches repair drones and hides behind scrap shields.',
  difficultyRole: 'Begins the new expansion by teaching tighter authored route reading.',
  journeyNote: 'Beyond the inferno lies the remains of a failed expedition, hinting at a larger war in deep space.',
  bgColor: '#03121a',
  accentColor: 0x5ee7d8,
  nebulaColor: 0x124b57,
  nebulaAlpha: 0.11,
  colorGrade: { brightness: 0.03, contrast: 1.1, saturation: 1.05 },
  planetPalette: [0x2a6f7c, 0x61b4c1],
  enemies: [
    { type: 'scout', weight: 20 },
    { type: 'fighter', weight: 32 },
    { type: 'bomber', weight: 12 },
    { type: 'swarm', weight: 8 },
    { type: 'gunship', weight: 28 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 1.96,
  levelDistance: 12600,
  hasBoss: true,
  boss: {
    name: 'Scrap Regent',
    maxHp: 86,
    phase1Cooldown: 860,
    phase2Cooldown: 420,
    phase2MoveSpeed: 215,
    attackStyle: 'pressure',
    phase1SpreadShotCount: 6,
    phase1SpreadArcDegrees: 64,
    phase1BulletSpeedScale: 1,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 96,
    phase2BulletSpeedScale: 1.06,
  },
  bossTriggerProgress: 0.66,
  asteroidInterval: 3200,
  sections: [
    {
      id: 'wreckfield-drift',
      label: 'Silent Hulks',
      startProgress: 0,
      endProgress: 0.24,
      phase: 'intro',
      summary: 'Derelict silhouettes create fake cover while gunships begin probing fire.',
      enemyFocus: [
        { type: 'scout', weight: 30 },
        { type: 'fighter', weight: 48 },
        { type: 'gunship', weight: 22 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.82,
      musicIntensity: 0.42,
    },
    {
      id: 'wreckfield-collapse',
      label: 'Collapse Lanes',
      startProgress: 0.24,
      endProgress: 0.58,
      phase: 'hazard',
      summary: 'Debris squeezes movement lanes while mixed enemy squads punish hesitation.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 16 },
        { type: 'gunship', weight: 30 },
        { type: 'scout', weight: 20 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 2.02,
      asteroidInterval: 2800,
      hazardEvents: [{ type: 'debris-surge', cadenceMs: 1900, intensity: 0.68 }],
      musicIntensity: 0.78,
    },
    {
      id: 'wreckfield-carrier-approach',
      label: 'Relay Threshold',
      startProgress: 0.58,
      endProgress: 0.66,
      phase: 'boss-approach',
      summary: 'The salvage fleet falls back and the carrier enters on a heavy cue.',
      musicIntensity: 0.9,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Broken Relay',
      mood: 'haunted momentum',
      tempoFeel: 'mid-tempo with sudden stress spikes',
      musicalStyle: 'metallic synth pulse with mournful lead fragments',
      intensity: 'medium-high',
      shiftMoments: ['Collapse lanes add harsher pulse accents.', 'Boss variant thickens the bass and accelerates the response loop.'],
      bossCueName: 'Broken Relay: Scrap Regent',
    },
    {
      tempo: 126,
      rootHz: 103.83,
      stepsPerBeat: 4,
      masterGain: 1.0,
      bass: {
        waveform: 'triangle',
        pattern: [0, null, null, null, 5, null, null, null, 7, null, null, null, 10, null, null, null],
        gain: 0.18,
        durationSteps: 3,
        filterHz: 1000,
      },
      pulse: {
        waveform: 'square',
        pattern: [12, null, null, 12, null, 10, null, null, 15, null, null, 12, null, 10, null, null],
        gain: 0.055,
        durationSteps: 1,
        octaveShift: 1,
        filterHz: 1900,
      },
      lead: {
        waveform: 'sine',
        pattern: [null, 17, null, null, null, 15, null, null, null, 19, null, null, null, 17, null, 12],
        gain: 0.04,
        durationSteps: 2,
        octaveShift: 1,
      },
      noise: {
        pattern: [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
        gain: 0.016,
        filterHz: 1800,
        durationSteps: 1,
      },
    },
    {
      tempo: 138,
      masterGain: 1.1,
      bass: { gain: 0.2 },
      pulse: { gain: 0.065 },
      lead: { waveform: 'triangle', gain: 0.05 },
      noise: { gain: 0.02, filterHz: 2400 },
    }
  ),
};
