import type { LevelConfig } from '../types';
import { createMusicProfile, layerExpressionPresets, noiseExpressionPresets, trackExpressionPresets, arpeggiatorPatterns, bassPatterns } from '../musicHelpers';

export const WRECKFIELD_RUN_LEVEL: LevelConfig = {
  name: 'Wreckfield Run',
  planetName: 'Orpheus Relay',
  destination: 'A broken convoy graveyard around Orpheus Relay',
  visualTheme: 'Faded teal wreckage, drifting hull silhouettes, and salvage sparks.',
  coreGameplayIdea: 'Debris navigation with enemy ambushes from blind wreck angles.',
  pacingSummary: 'Calm salvage drift, then collapsing wreck channels, then a carrier fight.',
  enemyCompositionSummary: 'Fighters and gunships spearhead the pressure while scouts fill gaps.',
  hazardSummary: 'Wreck fragments, debris surges, and salvage choke lanes.',
  bossConcept: 'A salvage carrier that launches repair drones and hides behind scrap shields.',
  difficultyRole: 'Begins the new expansion by teaching tighter authored route reading.',
  journeyNote: 'Beyond the inferno lies the remains of a failed expedition, hinting at a larger war in deep space.',
  bgColor: '#03121a',
  accentColor: 0x5ee7d8,
  nebulaColor: 0x124b57,
  nebulaAlpha: 0.11,
  colorGrade: { brightness: 0.03, contrast: 1.1, saturation: 1.05 },
  planetPalette: [0x2a6f7c, 0x61b4c1],
  enemies: [
    { type: 'scout', weight: 20 },
    { type: 'fighter', weight: 32 },
    { type: 'bomber', weight: 12 },
    { type: 'swarm', weight: 8 },
    { type: 'gunship', weight: 28 },
  ],
  encounterSize: { min: 2, max: 3 },
  spawnRateMultiplier: 1.96,
  levelDistance: 12600,
  hasBoss: true,
  boss: {
    name: 'Scrap Regent',
    maxHp: 86,
    phase1Cooldown: 860,
    phase2Cooldown: 420,
    phase2MoveSpeed: 215,
    attackStyle: 'pressure',
    phase1SpreadShotCount: 6,
    phase1SpreadArcDegrees: 64,
    phase1BulletSpeedScale: 1,
    phase2SpiralShotCount: 4,
    phase2SpiralTurnRate: 96,
    phase2BulletSpeedScale: 1.06,
  },
  bossTriggerProgress: 0.66,
  asteroidInterval: 3200,
  sections: [
    {
      id: 'wreckfield-drift',
      label: 'Silent Hulks',
      startProgress: 0,
      endProgress: 0.24,
      phase: 'intro',
      summary: 'Derelict silhouettes create fake cover while gunships begin probing fire.',
      enemyFocus: [
        { type: 'scout', weight: 30 },
        { type: 'fighter', weight: 48 },
        { type: 'gunship', weight: 22 },
      ],
      encounterSizeOverride: { min: 2, max: 2 },
      spawnRateMultiplier: 1.82,
      musicIntensity: 0.42,
    },
    {
      id: 'wreckfield-collapse',
      label: 'Collapse Lanes',
      startProgress: 0.24,
      endProgress: 0.58,
      phase: 'hazard',
      summary: 'Debris squeezes movement lanes while mixed enemy squads punish hesitation.',
      enemyFocus: [
        { type: 'fighter', weight: 34 },
        { type: 'bomber', weight: 16 },
        { type: 'gunship', weight: 30 },
        { type: 'scout', weight: 20 },
      ],
      encounterSizeOverride: { min: 2, max: 3 },
      spawnRateMultiplier: 2.02,
      asteroidInterval: 2800,
      hazardEvents: [{ type: 'debris-surge', cadenceMs: 1900, intensity: 0.68 }],
      musicIntensity: 0.78,
    },
    {
      id: 'wreckfield-carrier-approach',
      label: 'Relay Threshold',
      startProgress: 0.58,
      endProgress: 0.66,
      phase: 'boss-approach',
      summary: 'The salvage fleet falls back and the carrier enters on a heavy cue.',
      musicIntensity: 0.9,
    },
  ],
  music: createMusicProfile(
    {
      cueName: 'Broken Relay',
      mood: 'haunted momentum with melodic melancholy',
      tempoFeel: 'steady drift through drifting wreckage',
      musicalStyle: 'muted salvage pulse with mournful lead fragments and soft metallic dust',
      intensity: 'medium with melancholic swells',
      shiftMoments: ['Collapse lanes add denser melodic plucks.', 'Boss variant escalates through thicker scrap texture but keeps melodic flow.'],
      bossCueName: 'Broken Relay: Scrap Regent',
    },
    {
      tempo: 100,
      rootHz: 98,
      stepsPerBeat: 4,
      masterGain: 0.88,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        stereo: { ...trackExpressionPresets.expansiveSpace.stereo, width: 0.35, rateHz: 0.07 },
        accent: { amount: 0.06, patternBias: 0.14, emphasisSteps: [0, 8] },
      },
      bass: {
        waveform: 'sine',
        pattern: bassPatterns.gentlePulse(0),
        gain: 0.13,
        durationSteps: 4,
        filterHz: 850,
        expression: {
          ...layerExpressionPresets.longPad,
          ...layerExpressionPresets.ambientDrift,
          accent: { ...layerExpressionPresets.gentleAccent.accent, emphasisSteps: [0, 8] },
        },
      },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.flowing(12),
        gain: 0.032,
        durationSteps: 2,
        octaveShift: 1,
        filterHz: 1550,
        expression: {
          ...layerExpressionPresets.softPluck,
          ...layerExpressionPresets.orbit,
          accent: { amount: 0.08, patternBias: 0.14, emphasisSteps: [1, 8, 13] },
        },
      },
      lead: {
        waveform: 'sine',
        pattern: arpeggiatorPatterns.cascade(17),
        gain: 0.026,
        durationSteps: 3,
        octaveShift: 1,
        expression: {
          ...layerExpressionPresets.slowSwell,
          ...layerExpressionPresets.wideSpace,
          ...layerExpressionPresets.gentleVibrato,
        },
      },
      noise: {
        pattern: [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
        gain: 0.01,
        filterHz: 1400,
        durationSteps: 1,
        expression: {
          ...noiseExpressionPresets.softAir,
          stereo: { ...noiseExpressionPresets.softAir.stereo, width: 0.25, rateHz: 0.05 },
        },
      },
    },
    {
      tempo: 108,
      masterGain: 0.94,
      expression: {
        ...trackExpressionPresets.expansiveSpace,
        ...trackExpressionPresets.chase,
        modulation: { ...trackExpressionPresets.chase.modulation, depth: 200, rateHz: 0.85 },
        accent: { amount: 0.12, patternBias: 0.24, emphasisSteps: [0, 4, 8, 12] },
      },
      bass: { gain: 0.15, filterHz: 950 },
      pulse: {
        waveform: 'triangle',
        pattern: arpeggiatorPatterns.upDownTriad(12),
        gain: 0.04,
      },
      lead: { waveform: 'sine', gain: 0.032 },
      noise: {
        gain: 0.013,
        filterHz: 1900,
        expression: {
          ...noiseExpressionPresets.shimmer,
          accent: { amount: 0.08, patternBias: 0.16, emphasisSteps: [2, 6, 10, 14] },
        },
      },
    }
  ),
};
